### ISSUE TITLE
Avatar on iOS v2.1

### ISSUE THREAD

**Issue by djorkaeffalexandre** [skrafft/react-native-jitsi-meet#102]
Hey @skrafft!
I don't have much time on this week, then I'll describe it here just FYI, if I have some time on this weekend I can open a PR.
[Here](https://github.com/skrafft/react-native-jitsi-meet/blob/master/ios/RNJitsiMeetViewManager.m#L39) you need to cast from `NSString` to `NSUrl` because `avatar` on `JitsiMeetUserInfo` is a `NSUrl`. :)
You can check [here](https://github.com/jitsi/jitsi-meet/blob/e33b334307e4086041f3b736eb89071b7dcd54d1/ios/sdk/src/JitsiMeetUserInfo.m#L46), `absoluteString` is a method to extract string from `NSUrl`.

**Comment by skrafft** [comment]
Hi @djorkaeffalexandre ,

Thanks for the feedback. I've fixed the problem in v2.1.1.
