### ISSUE TITLE
Bitcode Missing

### ISSUE THREAD

**Issue by jplandry908** [skrafft/react-native-jitsi-meet#108]
FYI - The bitcode appears to be missing from this package. A workaround for anyone experiencing this error is to disable bitcode for the target.

**Compile Error:**
ld: '../ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/JitsiMeet' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '../ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/JitsiMeet' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by lironsher** [comment]
set enable bitcode - no 
(in the readme)
