### ISSUE TITLE
build ios device error [ clang: error: linker command failed with exit code 1 ]

### ISSUE THREAD

**Issue by abhiwich** [skrafft/react-native-jitsi-meet#11]
Hello 

I have configured your document about react-native-jitsi-meet.
I have experimented with my iphone and tried to adapt to your requirements.
Clang: error: linker failed with exit code 1 (use -v to see invocation)
I hope you can tell me the problem.

Did I show you my structure initially, right?
And I do not have the libstdc++.tbd  I replaced it to  libc++.tbd file.

![2](https://user-images.githubusercontent.com/2469771/48304436-1eb12080-e54c-11e8-813a-f6d0d70c6d16.jpg)
![3](https://user-images.githubusercontent.com/2469771/48304437-1eb12080-e54c-11e8-96e4-8d417c164e71.jpg)
![4](https://user-images.githubusercontent.com/2469771/48304464-7c456d00-e54c-11e8-8eb3-acbf2a31299b.jpg)

Thank You

**Comment by skrafft** [comment]
Your compilation fails because you have included react-native-jitsi-meet files twice, once in Libraries by including RNJitsiMeet.xcodeproj and once in your source files. You have to remove the following files from your source files:

- JitsiMeetViewController.h
- JitsiMeetViewController.m
- RNJitsiMeet.m
- RNJitsiMeetNavigator.h
- RNJitsiMeetNavigator.m

The only file that has to stay in place is JitsiMeet.storyboard

**Comment by abhiwich** [comment]
Thank you for your advice
I've edited as you suggested and experimented on ios the device. 
Something went wrong.

Conference[1525:715837] [] __nw_connection_get_connected_socket_block_invoke xxx Connection has no connected handler

![5](https://user-images.githubusercontent.com/2469771/48315786-42886b00-e60d-11e8-870a-3d81920fc292.jpg)
![6](https://user-images.githubusercontent.com/2469771/48315787-42886b00-e60d-11e8-89a4-96720a7f5587.jpg)
![7](https://user-images.githubusercontent.com/2469771/48315788-42886b00-e60d-11e8-8abd-302a30a5f788.jpg)

**Comment by skrafft** [comment]
Hi,

You can ignore the warnings. Sorry but I could not understand if your app is working or not ?

**Comment by abhiwich** [comment]
Hi, skrafft 
Now I do not succeed.

Output log console display:

2561-11-15 04:59:36.404 [info][tid:main][RCTRootView.m:293] Running application Conference ({
    initialProps =     {
    };
    rootTag = 1;
})
2561-11-15 04:59:38.140 [info][tid:com.facebook.react.JavaScript] Running application "Conference" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF

**Comment by skrafft** [comment]
Hi,
These are just usual messages. What problem are you encountering ?

**Comment by skrafft** [comment]
No answer, closing

**Comment by saadqbal** [comment]
Hey @abhiwich , Did you ever try JistiMeet together with realm database? I have been trying but stuck with it.
