### ISSUE TITLE
using 2.6.0 sdk 

### ISSUE THREAD

**Issue by batuhansahan** [skrafft/react-native-jitsi-meet#111]
There is a problem with sdk 2.6.0 how can i resolve, anyone can help me about that.

**Comment by lironsher** [comment]
?

**Comment by batuhansahan** [comment]
```
 implementation(project(':react-native-jitsi-meet')) {
      //...
      exclude group: 'com.facebook',module:'hermes'
}
```

**Comment by LeoMosiah** [comment]
I tried this @batuhansahan , but when I try to open the menu inside the conference the app crashes.

**Comment by batuhansahan** [comment]
check your dependencies and exclude them if jitsi-meet uses it  [jitsi-maven-repository](https://github.com/jitsi/jitsi-maven-repository/tree/master/releases/com/facebook/react)
