### ISSUE TITLE
Could not find org.jitsi.react:jitsi-meet-sdk:2.4.0

### ISSUE THREAD

**Issue by bonafidehan** [skrafft/react-native-jitsi-meet#113]
Versions:

> "react-native": "0.61.5",`
> "react-native-jitsi-meet": "^2.1.1"

Followed the instructions in https://github.com/skrafft/react-native-jitsi-meet/issues/67#issuecomment-547913666. But still getting the same error. This is a brand new RN project with just react-native-jitsi-meet added.

Error:
> FAILURE: Build failed with an exception.
>
> * What went wrong:
> Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find org.jitsi.react:jitsi-meet-sdk:2.4.0.
     Searched in the following locations:
       - file:/home/han/.m2/repository/org/jitsi/react/jitsi-meet-sdk/2.4.0/jitsi-meet-sdk-2.4.0.pom
       - file:/home/han/.m2/repository/org/jitsi/react/jitsi-meet-sdk/2.4.0/jitsi-meet-sdk-2.4.0.jar
       - file:/home/han/Dropbox/git/hb/beam/node_modules/react-native/android/org/jitsi/react/jitsi-meet-sdk/2.4.0/jitsi-meet-sdk-2.4.0.pom
       - file:/home/han/Dropbox/git/hb/beam/node_modules/react-native/android/org/jitsi/react/jitsi-meet-sdk/2.4.0/jitsi-meet-sdk-2.4.0.jar
       - file:/home/han/Dropbox/git/hb/beam/node_modules/jsc-android/dist/org/jitsi/react/jitsi-meet-sdk/2.4.0/jitsi-meet-sdk-2.4.0.pom
       - file:/home/han/Dropbox/git/hb/beam/node_modules/jsc-android/dist/org/jitsi/react/jitsi-meet-sdk/2.4.0/jitsi-meet-sdk-2.4.0.jar
       - https://dl.google.com/dl/android/maven2/org/jitsi/react/jitsi-meet-sdk/2.4.0/jitsi-meet-sdk-2.4.0.pom
       - https://dl.google.com/dl/android/maven2/org/jitsi/react/jitsi-meet-sdk/2.4.0/jitsi-meet-sdk-2.4.0.jar
       - https://jcenter.bintray.com/org/jitsi/react/jitsi-meet-sdk/2.4.0/jitsi-meet-sdk-2.4.0.pom
       - https://jcenter.bintray.com/org/jitsi/react/jitsi-meet-sdk/2.4.0/jitsi-meet-sdk-2.4.0.jar
       - https://jitpack.io/org/jitsi/react/jitsi-meet-sdk/2.4.0/jitsi-meet-sdk-2.4.0.pom
       - https://jitpack.io/org/jitsi/react/jitsi-meet-sdk/2.4.0/jitsi-meet-sdk-2.4.0.jar
     Required by:
         project :app > project :react-native-jitsi-meet

**Comment by skrafft** [comment]
I don't see the jitsi repo listed in your maven repositories, can you check that you followed the install howto correctly (especially part 3): https://github.com/skrafft/react-native-jitsi-meet#android-manual-install

**Comment by bonafidehan** [comment]
Got it, I may have missed that step. I'll close this issue and reopen if I encounter anything. Thanks a bunch for the help!
