### ISSUE TITLE
Problem with Jitsi integration on my react native android app

### ISSUE THREAD

**Issue by torugor** [skrafft/react-native-jitsi-meet#114]
First i will tell my version:
react-native-cli: 2.0.1
react-native: 0.59.8

I presumed i had to Use (< 2.0.0 and RN<0.60) instructions so i did:
1- npm install react-native-jitsi-meet --save
2- created an empty component and tested it  OK
then I imported: import JitsiMeet, { JitsiMeetEvents } from 'react-native-jitsi-meet';
and the component started giving me 
null is not an object (evaluating 'JistsiMeetModule.call')

Here my component:
import React, {Component} from 'react';
import {Platform, TouchableHighlight,Image,Alert,ActivityIndicator,StyleSheet, Text,TextInput, View,ImageBackground, Button} from 'react-native';
import JitsiMeet, { JitsiMeetEvents } from 'react-native-jitsi-meet';
/*const initiateVideoCall = () => {
    JitsiMeet.initialize();
    console.log('JITSI inicializado')
    JitsiMeetEvents.addListener('CONFERENCE_LEFT', (data) => {
      console.log('CONFERENCE_LEFT');
    });
    setTimeout(() => {
      JitsiMeet.call("https://meet.jit.si/teste");
    }, 1000);
  };
*/
export default class VideoCall extends Component {
  constructor(){
    super()
  }

  componentDidMount(){
  };

///////////////////////////

  render() {
    const {scrollToInput, onDropdownClose, onDropdownShow} = this.props; 
    return (
      <ImageBackground   source={require('../../assets/Welcome.png')} style={{width: '100%', height: '100%'}}>

      </ImageBackground>
      
    );
  }

}

Any idea on what is going on wrong?

**Comment by rcidt** [comment]
1. Please be more clear. State what exactly the issue is. Are there any error logs?
2. Format your code, it is very hard to read.

**Comment by skrafft** [comment]
Hi @torugor ,

If you are using RN < 0.60, you have to use react-native-jitsi-meet 1.2.0. Keep in mind that this version is not compatible with iOS 13.

If you want to use latest jitsi meet version, you have to use version 2.1.1 of react-native-jitsi-meet and upgrade your RN version to 0.60.6.
