### ISSUE TITLE
Video not showing on iOS

### ISSUE THREAD

**Issue by ankitbisht143** [skrafft/react-native-jitsi-meet#115]
Hi, I am using react-native-jitsi-meet@1.2.0 since my RN version < 0.60. But video is not showing on iOS. Its just a audio call.

**Code**
JitsiMeet.initialize();
JitsiMeet.call(meetingUrl);

**Comment by skrafft** [comment]
Hi @ankitbisht143,

Sadly, v1.2.0 is not compatible with iOS 13, that's why you don't have any video. The video works on android and iOS < 13 though. The only option is to upgrade your RN version and switch to a higher version of this library.
