### ISSUE TITLE
End call when the app is manually killed on android

### ISSUE THREAD

**Issue by rcidt** [skrafft/react-native-jitsi-meet#119]
I am seeing the following behavior:

On android, start a call, then close the app from the activity manager while the call is ongoing.

The call does not end and you can still hear and people can hear you.

If you come back to the app it doesn't let you enter another call. The only way to stop the call is to "Force Stop" the app by going into the app info page.

Is there a way to handle this type of situation?

**Comment by skrafft** [comment]
@rcidt 

I guess you could listen to AppState change events and terminate the call if there is one:

```
componentDidMount() {
  AppState.addEventListener('change', this.handleAppStateChange);
}

componentWillUnmount() {
  AppState.removeEventListener('change', this.handleAppStateChange);
}

handleAppStateChange = (nextAppState) => {
  if (nextAppState === 'inactive') {
    console.log('the app is closed');
  }    
}
```

**Comment by rcidt** [comment]
@skrafft thanks, I was wondering if this was the best way to do it.
