### ISSUE TITLE
Some questions 

### ISSUE THREAD

**Issue by roy2651** [skrafft/react-native-jitsi-meet#12]
hi，buddy
this‘s great，and now I’m using it。
But is this have change displayname api and other jitsi-meet apis，
is this have a   JitsiMeet.call()

**Comment by roy2651** [comment]
Hi skrafft:
when I run in android 5 , it is ok;
and I run in android 7.1.2, it will carsh.
is this my device problem or this wrapper's problem
please help me

**Comment by skrafft** [comment]
Hi,

Without logs, I can't tell you where the problem is.

Can you post logs here ?

**Comment by roy2651** [comment]
@skrafft android7 is ok！
my fault！
I run this app in android box
and I find this has some lag，
you have some recommend？
and this wrapper has some other api？

**Comment by skrafft** [comment]
Hi, There's no other api for now. Feel free to fork the project and make a pull request if you need more features.

**Comment by roy2651** [comment]
@skrafft OK，thank you！
