### ISSUE TITLE
 Android application startup problem

### ISSUE THREAD

**Issue by joaodematejr** [skrafft/react-native-jitsi-meet#127]
Follow the tutorial but when I start the application it closes without showing any error, I'm using the flipper to debug this only happens on the android version	

"react": "16.11.0",
"react-native": "0.62.2",
"react-native-jitsi-meet": "^2.1.1",

16:20:44.195	AndroidRuntime	FATAL EXCEPTION: pool-5-thread-1
Process: com.covidbr, PID: 29197
java.lang.UnsatisfiedLinkError: No implementation found for void org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals() (tried Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals and Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals__)
	at org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals(Native Method)
	at org.webrtc.PeerConnectionFactory.initialize(PeerConnectionFactory.java:283)
	at com.oney.WebRTCModule.WebRTCModule.initAsync(WebRTCModule.java:82)
	at com.oney.WebRTCModule.WebRTCModule.lambda$new$0$WebRTCModule(WebRTCModule.java:73)
	at com.oney.WebRTCModule.WebRTCModule$$Lambda$0.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

**Comment by ffrappo** [comment]
Hello @joaodematejr we also run into this issue. Essentially, you have to follow the "Side Notes" here, for any component that could be already into your project.

https://github.com/skrafft/react-native-jitsi-meet#side-note

**Comment by felipebastosb** [comment]
I'm facing the same error and the project doesn't contain any of these modules. I tried a new project that just contains Jitsi Meet and  the error persists.

**Comment by felipebastosb** [comment]
@joaodematejr I solved the problem by changing the `minSdkVersion` to `24` at `android/build.gradle` as discussed in issue #133

**Comment by joaodematejr** [comment]
@felipebastosb Thanks !

**Comment by lamualfa** [comment]
> Hello @joaodematejr we also run into this issue. Essentially, you have to follow the "Side Notes" here, for any component that could be already into your project.
> 
> https://github.com/skrafft/react-native-jitsi-meet#side-note
> 
> `android/app/build.gradle`
> 
> inside
> dependencies {
> implementation project(':react-native-device-info')
> ...
> add the block below here
> }
> 
> ```
>     implementation(project(':react-native-jitsi-meet')) {
>       exclude group: 'com.facebook.react',module:'react-native-locale-detector'
>       exclude group: 'com.facebook.react',module:'react-native-vector-icons'
>       exclude group: 'com.facebook.react',module:'react-native-fetch-blob'
>       exclude group: 'com.facebook.react',module:'react-native-webview'
>       exclude group: 'com.facebook.react',module:'react-native-community-async-storage'
>     }
> ```
> 
> Be sure to only exclude possibly duplicated modules!

How do I know that a related package has potential duplicates?

**Comment by joaodematejr** [comment]
> @joaodematejr
> How do I know that a related package has potential duplicates?

Using the npx react-native run-android command, if there is a package duplicate, it will warn and will not let the project run.
