### ISSUE TITLE
Send password in the JitsiMeet.call

### ISSUE THREAD

**Issue by StavSheiz** [skrafft/react-native-jitsi-meet#131]
Hi

Is it possible to add an option to send the password for a meeting in the JitsiMeet.call function instead of having the user type it?

Example: 
`JitsiMeet.call(url, userInfo, password)`

Thanks!

**Comment by lamualfa** [comment]
This library is just a wrapper from the main Jitsi SDK written with Java . For more features, go to their main [repository](https://github.com/jitsi/jitsi-meet/blob/master/android/README.md#use-pre-build-sdk-artifactsbinaries). Please close this issue.
