### ISSUE TITLE
Install Error on iOS

### ISSUE THREAD

**Issue by j-cimb-barker** [skrafft/react-native-jitsi-meet#137]
Hello,

I am trying to use react-native-jitsi-meet on IOS with React.

Without running "pod install" I get the following error:

```
TypeError: null is not an object (evaluating 'JitsiMeetModule.call')

<global>
    index.ios.js:9:28
loadModuleImplementation
    require.js:321:11
<global>
    App.js:27
loadModuleImplementation
    require.js:321:11
<global>
    index.js:6
loadModuleImplementation
    require.js:321:11
guardedLoadModule
    require.js:201:44
global code
    index.bundle?platform=ios&dev=true&minify=false:104819:3
```

If I run pod install in the ios folder I get:

```
[!] CocoaPods could not find compatible versions for pod "JitsiMeetSDK":
  In Podfile:
    react-native-jitsi-meet (from `../node_modules/react-native-jitsi-meet`) was resolved to 2.1.1, which depends on
      JitsiMeetSDK (= 2.4.0)

Specs satisfying the `JitsiMeetSDK (= 2.4.0)` dependency were found, but they required a higher minimum deployment target.
```

I copied and pasted the contents of metro.config.js from the ReadMe into metro.config.js but this has no change.

Versions:

    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-jitsi-meet": "^2.1.1"

Any help appreciated...!

**Comment by TnasuH** [comment]
> Hello,
> 
> I am trying to use react-native-jitsi-meet on IOS with React.
> 
> Without running "pod install" I get the following error:
> 
> ```
> TypeError: null is not an object (evaluating 'JitsiMeetModule.call')
> 
> <global>
>     index.ios.js:9:28
> loadModuleImplementation
>     require.js:321:11
> <global>
>     App.js:27
> loadModuleImplementation
>     require.js:321:11
> <global>
>     index.js:6
> loadModuleImplementation
>     require.js:321:11
> guardedLoadModule
>     require.js:201:44
> global code
>     index.bundle?platform=ios&dev=true&minify=false:104819:3
> ```
> 
> If I run pod install in the ios folder I get:
> 
> ```
> [!] CocoaPods could not find compatible versions for pod "JitsiMeetSDK":
>   In Podfile:
>     react-native-jitsi-meet (from `../node_modules/react-native-jitsi-meet`) was resolved to 2.1.1, which depends on
>       JitsiMeetSDK (= 2.4.0)
> 
> Specs satisfying the `JitsiMeetSDK (= 2.4.0)` dependency were found, but they required a higher minimum deployment target.
> ```
> 
> I copied and pasted the contents of metro.config.js from the ReadMe into metro.config.js but this has no change.
> 
> Versions:
> 
> ```
> "react": "16.11.0",
> "react-native": "0.62.2",
> "react-native-jitsi-meet": "^2.1.1"
> ```
> 
> Any help appreciated...!

me too.

**Comment by j-cimb-barker** [comment]
Ok, I actually read the readme this time. This is working now.

**Comment by shamoons** [comment]
I have the same issue, but I thought the `Info.plist` was only for RN < 0.60?

**Comment by trinhak** [comment]
change:  platform :ios, '10.0' in Podfile

**Comment by dfabreguette-ap** [comment]
If you use expo (like me) only solution I found was ejecting the app (generating ios / android projects) and then run the project with xcode / android studio.
Looks like external modules are not working fine with expo : https://expo.canny.io/feature-requests/p/webrtc
