### ISSUE TITLE
Does this SDK work on windows development environment?

### ISSUE THREAD

**Issue by shareef-dweikat** [skrafft/react-native-jitsi-meet#139]
Hey There
Thank you for your incurable work.
I am developing a react native app using widows, is it possible to use your SDK in widows development environment? Cause i just saw a comment on jetsi official repository says that the SDK can't be built on windows. Does this go for your SDK as well?

**Comment by batuhansahan** [comment]
this is not a sdk repository it is bridge between your app and [jitsi sdk](https://github.com/jitsi/jitsi-maven-repository/tree/master/releases) you can use this library as mention readme.md on Windows,  

not: This library is just example of implementation, also you can set up yourself A CUSTOM SDK(means you can customize ui) [android custom sdk guide](https://github.com/jitsi/jitsi-meet/blob/master/android/README.md)

**Comment by shareef-dweikat** [comment]
@batuhansahan 
Thank You. Its working perfectly on my windows.
I have  another question please, how can i show conference video on the phone? nothing appears on my phone screen! I can hear others, and they can hear and see my. But i cant see them.

**Comment by batuhansahan** [comment]
Have you implement this ?
```jsx
      <View style={{ backgroundColor: 'black',flex: 1 }}>
        <JitsiMeetView 
            onConferenceTerminated={this.onConferenceTerminated} 
            onConferenceJoined={this.onConferenceJoined} 
            onConferenceWillJoin={this.onConferenceWillJoin} style={{ flex: 1, height: '100%', width: '100%' }} />
      </View>
```

if you have please share your code so i can help also share your dependencies

**Comment by shareef-dweikat** [comment]
I solved It By removing the flex in View and JistiMeetView. Its working now, thank you.
