### ISSUE TITLE
Is it possible to add options to the call? Like mute, turn off camera,...etc

### ISSUE THREAD

**Issue by shareef-dweikat** [skrafft/react-native-jitsi-meet#140]
Is it possible to add options to the call? Like mute, turn off camera,...etc.

**Comment by batuhansahan** [comment]
you can use `JitsiMeet.audioCall()` instead of `JitsiMeet.call()`

**Comment by shareef-dweikat** [comment]
@batuhansahan 
What i understood is that we cant customize UI using React Native, because Jitsi does not allow it. But we can customize it using native code (Java and Swift). 

Correct me please if i am wrong.

**Comment by batuhansahan** [comment]
No, you are wrong, here is actually sdk itself [Jitsi-meet](https://github.com/jitsi/jitsi-meet) please check this repo its all javascript, and read the guide, there is react folder and every mobile ui component is in there, fork the repo and customize it, and [build the sdk](https://github.com/jitsi/jitsi-meet/blob/master/android/README.md#build-and-use-your-own-sdk-artifactsbinaries)

**Comment by shareef-dweikat** [comment]
You said in #128 "its not possible because Jitsi SDK didn't expose these features"
What features you mean?

So sorry for troubling you.

![Capture](https://user-images.githubusercontent.com/10628302/79766771-16f4ce80-8331-11ea-9b5d-9114e58cc093.PNG)

**Comment by batuhansahan** [comment]
> You said in #128 "its not possible because Jitsi SDK didn't expose these features"
> What features you mean?
> 
> So sorry for troubling you.
> 
> ![Capture](https://user-images.githubusercontent.com/10628302/79766771-16f4ce80-8331-11ea-9b5d-9114e58cc093.PNG)

[these are](https://github.com/skrafft/react-native-jitsi-meet/issues/128#issuecomment-616021584)

**Comment by shareef-dweikat** [comment]
@batuhansahan 
I think i get the idea now. I needed time to take everything  in my mind. Thanks a lot.

**Comment by batuhansahan** [comment]
> @batuhansahan
> I think i get the idea now. I needed time to take everything in my mind. Thanks a lot.

this is [Community Forum](https://community.jitsi.org/) good place to learn more about jitsi, you should visit also you can post your questions, they are people happy to help you.

**Comment by shareef-dweikat** [comment]
Thanks a lot.
