### ISSUE TITLE
npm ERR! code E404

### ISSUE THREAD

**Issue by rakibulinux** [skrafft/react-native-jitsi-meet#142]
I got the error to use this command
npm install react-native-jitsi-meet.podspec --save

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/react-native-jitsi-meet.podspec - Not found
npm ERR! 404 
npm ERR! 404  'react-native-jitsi-meet.podspec@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by lamualfa** [comment]
`react-native-jitsi-meet.podspec` is not a library. See this [answer](https://stackoverflow.com/a/14003781/10861398) to find out "what is `.podspec` file?". You can find the `.podspec` file for this library in the [main repository](https://github.com/skrafft/react-native-jitsi-meet). its location is at the bottom. Please close this issue immediately.

**Comment by rakibulinux** [comment]
I fixed this Error but was got a new error

**Comment by lamualfa** [comment]
> I fixed this Error but was got a new error

Please close this issue and create new one with related error.

**Comment by react06** [comment]
Mine worked with this command.
`sudo chown -R 1089639986:2055167320 "/Users/riya.n/MyProjects/Demo/C:\\Users\\mycomputer~1name\\AppData\\Roaming\\npm-cache"`
