### ISSUE TITLE
My app is closing when I try to open jitsi meet

### ISSUE THREAD

**Issue by Lorenalgm** [skrafft/react-native-jitsi-meet#147]
Hi! I’m working on a react native app and I want to use Jitsi Meet there. I already did all of the steps mentioned in read me, but when I run the app, I got the errror:
TypeError: null is not an object (evaluating JitsiMeetModule.Call)

![image](https://user-images.githubusercontent.com/19291466/80399133-16a78680-888f-11ea-8bd4-c09b6ea2086c.png)

How can I solved it?

`import JitsiMeet, { JitsiMeetView } from 'react-native-jitsi-meet';

The problem is with JitsiMeet.call:
```
  useEffect(() => {
    setTimeout(() => {
      const url = 'https://meet.jit.si/exemple';
      const userInfo = {
        displayName: 'User',
        email: 'user@example.com',
        avatar: 'https:/gravatar.com/avatar/abc123',
      };
      JitsiMeet.call(url, userInfo);
    }, 1000);
  }, []);
```

And then I try:

`  return (
    <>
      <View>
        <Container>
          <TitleSalutation>Bem-vindo</TitleSalutation>
          <JitsiMeetView
          style={{
            flex: 1,
            height: '100%',
            width: '100%',
          }}
        />
        </Container>
      </View>
    </>
  );
}`

**Comment by Lorenalgm** [comment]
I solved this problem! But now I'm with another problem, when I open Jitsi in my app, the app just close. Any ideas?

**Comment by antoinefotso** [comment]
@Lorenalgm try set minSDKversion to 24 and try again

**Comment by Lorenalgm** [comment]
Thanks! Actually the problem was Codepush, which was interfering in some way with the jitisi. I removed Codepush for now and it worked just fine

**Comment by katinc** [comment]
Hey @Lorenalgm , i know it's been a while but can you share how you resolved the original issue. 
Thanks.
