### ISSUE TITLE
App Crash In Release mode

### ISSUE THREAD

**Issue by Punit-Vajpeyi** [skrafft/react-native-jitsi-meet#171]
Application Crashing:

06-07 21:03:46.860 23017 23115 E ReactNativeJS: TypeError: Cannot read property 'call' of null
06-07 21:03:46.862 23017 23115 E ReactNativeJS: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
--------- beginning of crash
06-07 21:03:46.868 23017 23116 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
06-07 21:03:46.868 23017 23116 E AndroidRuntime: Process: com.jitsidemo, PID: 23017
06-07 21:03:46.868 23017 23116 E AndroidRuntime: com.facebook.react.common.JavascriptException: TypeError: Cannot read property 'call' of null, js engine: hermes, stack:
06-07 21:03:46.868 23017 23116 E AndroidRuntime: anonymous@406:277
06-07 21:03:46.868 23017 23116 E AndroidRuntime: v@2:1473
06-07 21:03:46.868 23017 23116 E AndroidRuntime: d@2:945
06-07 21:03:46.868 23017 23116 E AndroidRuntime: o@2:413
06-07 21:03:46.868 23017 23116 E AndroidRuntime: anonymous@405:228
06-07 21:03:46.868 23017 23116 E AndroidRuntime: v@2:1473
06-07 21:03:46.868 23017 23116 E AndroidRuntime: d@2:945
06-07 21:03:46.868 23017 23116 E AndroidRuntime: o@2:413
06-07 21:03:46.868 23017 23116 E AndroidRuntime: anonymous@396:150
06-07 21:03:46.868 23017 23116 E AndroidRuntime: v@2:1473
06-07 21:03:46.868 23017 23116 E AndroidRuntime: d@2:945
06-07 21:03:46.868 23017 23116 E AndroidRuntime: o@2:413
06-07 21:03:46.868 23017 23116 E AndroidRuntime: anonymous@6:57
06-07 21:03:46.868 23017 23116 E AndroidRuntime: v@2:1473
06-07 21:03:46.868 23017 23116 E AndroidRuntime: d@2:875
06-07 21:03:46.868 23017 23116 E AndroidRuntime: o@2:413
06-07 21:03:46.868 23017 23116 E AndroidRuntime: global@409:3
06-07 21:03:46.868 23017 23116 E AndroidRuntime: 
06-07 21:03:46.868 23017 23116 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:79)
06-07 21:03:46.868 23017 23116 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-07 21:03:46.868 23017 23116 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
06-07 21:03:46.868 23017 23116 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
06-07 21:03:46.868 23017 23116 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
06-07 21:03:46.868 23017 23116 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
06-07 21:03:46.868 23017 23116 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
06-07 21:03:46.868 23017 23116 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
06-07 21:03:46.868 23017 23116 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
06-07 21:03:46.868 23017 23116 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
06-07 21:03:46.868 23017 23116 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: com.facebook.react.common.JavascriptException: TypeError: Cannot read property 'call' of null, js engine: hermes, stack:
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: anonymous@406:277
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: v@2:1473
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: d@2:945
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: o@2:413
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: anonymous@405:228
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: v@2:1473
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: d@2:945
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: o@2:413
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: anonymous@396:150
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: v@2:1473
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: d@2:945
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: o@2:413
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: anonymous@6:57
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: v@2:1473
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: d@2:875
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: o@2:413
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: global@409:3
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:79)
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 	at java.lang.reflect.Method.invoke(Native Method)
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 	at android.os.Handler.handleCallback(Handler.java:883)
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 	at android.os.Handler.dispatchMessage(Handler.java:100)
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 	at android.os.Looper.loop(Looper.java:237)
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 	at java.lang.Thread.run(Thread.java:919)
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: com.facebook.react.common.JavascriptException: TypeError: Cannot read property 'call' of null, js engine: hermes, stack:
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: anonymous@406:277
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: v@2:1473
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: d@2:945
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: o@2:413
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: anonymous@405:228
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: v@2:1473
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: d@2:945
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: o@2:413
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: anonymous@396:150
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: v@2:1473
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: d@2:945
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: o@2:413
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: anonymous@6:57
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: v@2:1473
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: d@2:875
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: o@2:413
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: global@409:3
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:79)
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 	at java.lang.reflect.Method.invoke(Native Method)
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 	at android.os.Handler.handleCallback(Handler.java:883)
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 	at android.os.Handler.dispatchMessage(Handler.java:100)
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 	at android.os.Looper.loop(Looper.java:237)
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
06-07 21:03:46.869 23017 23116 E JitsiMeetSDK: 	at java.lang.Thread.run(Thread.java:919)

**Comment by hasgardee** [comment]
@Punit-Vajpeyi how did you fix this issue? I'm also facing the same

**Comment by Punit-Vajpeyi** [comment]
It was the configuration issue for me. I missed one step of readme which was giving me the problem.

**Comment by hasgardee** [comment]
@Punit-Vajpeyi  which step was you missing? are you using hermes?

**Comment by Punit-Vajpeyi** [comment]
Yes, I am using Hermes. Changes in MainApplication

          @Override
          protected @Nullable String getBundleAssetName() {
              return "app.bundle";
          }

**Comment by hasgardee** [comment]
@Punit-Vajpeyi which is already done. for me which is working in debugging but note in release.

**Comment by hasgardee** [comment]
Finally fixed it. `react-native-codepush` was causing issues for me.
