### ISSUE TITLE
Is there anyway to hide some functions

### ISSUE THREAD

**Issue by hnrqsss** [skrafft/react-native-jitsi-meet#177]
Hello first i'd like you for this project!

Is there anyway to hide chat and the option buttons?

**Comment by RicardoDolNL** [comment]
You'll need to fork this github project and than edit RNJitsiMeetModule.java and RNJitsiMeetViewManager.m.
Within those files you'll find a section with JitsiMeetConferenceOptions. You can set the so called 'setFeatureFlag' to enable or disable some features.

Android example:
```
RNJitsiMeetConferenceOptions options = new RNJitsiMeetConferenceOptions.Builder()
        .setRoom(url)
        .setUserInfo(_userInfo)
        .setAudioOnly(false)
        .setFeatureFlag("add-people.enabled", false)
        .setFeatureFlag("live-streaming.enabled", false)
        .setFeatureFlag("meeting-password.enabled", false)
        .setFeatureFlag("recording.enabled", false)
        .setFeatureFlag("invite.enabled", false)
        .build();
mJitsiMeetViewReference.getJitsiMeetView().join(options);
```

iOS example:
```
JitsiMeetConferenceOptions *options = [JitsiMeetConferenceOptions fromBuilder:^(JitsiMeetConferenceOptionsBuilder *builder) {
        builder.room = urlString;
        builder.userInfo = _userInfo;
        [builder setFeatureFlag:@"add-people.enabled" withBoolean:NO];
        [builder setFeatureFlag:@"ios.recording.enabled" withBoolean:NO];
        [builder setFeatureFlag:@"live-streaming.enabled" withBoolean:NO];
        [builder setFeatureFlag:@"meeting-password.enabled" withBoolean:NO];
        [builder setFeatureFlag:@"invite.enabled" withBoolean:NO];
}];
[jitsiMeetView join:options];
```

**Comment by hnrqsss** [comment]
> You'll need to fork this github project and than edit RNJitsiMeetModule.java and RNJitsiMeetViewManager.m.
> Within those files you'll find a section with JitsiMeetConferenceOptions. You can set the so called 'setFeatureFlag' to enable or disable some features.
> 
> Android example:
> 
> ```
> RNJitsiMeetConferenceOptions options = new RNJitsiMeetConferenceOptions.Builder()
>         .setRoom(url)
>         .setUserInfo(_userInfo)
>         .setAudioOnly(false)
>         .setFeatureFlag("add-people.enabled", false)
>         .setFeatureFlag("live-streaming.enabled", false)
>         .setFeatureFlag("meeting-password.enabled", false)
>         .setFeatureFlag("recording.enabled", false)
>         .setFeatureFlag("invite.enabled", false)
>         .build();
> mJitsiMeetViewReference.getJitsiMeetView().join(options);
> ```
> 
> iOS example:
> 
> ```
> JitsiMeetConferenceOptions *options = [JitsiMeetConferenceOptions fromBuilder:^(JitsiMeetConferenceOptionsBuilder *builder) {
>         builder.room = urlString;
>         builder.userInfo = _userInfo;
>         [builder setFeatureFlag:@"add-people.enabled" withBoolean:NO];
>         [builder setFeatureFlag:@"ios.recording.enabled" withBoolean:NO];
>         [builder setFeatureFlag:@"live-streaming.enabled" withBoolean:NO];
>         [builder setFeatureFlag:@"meeting-password.enabled" withBoolean:NO];
>         [builder setFeatureFlag:@"invite.enabled" withBoolean:NO];
> }];
> [jitsiMeetView join:options];
> ```

Thank you !!!
