### ISSUE TITLE
Crash on Android, possible conflict with react-native-firebase plugin

### ISSUE THREAD

**Issue by RicardoBer** [skrafft/react-native-jitsi-meet#18]
I install your plugin in an app that uses react-native-firebase too.

I has not problems with firebase and recives notifications and messages without problems.

When I put a button on view and onPress call your example function the app crashes:

The code in react native app is:

JSX:
`onPress={ () => {this.iniciaVideoLlamada()} }>`

Js:
```
iniciaVideoLlamada = () => {
    JitsiMeet.initialize();
    JitsiMeetEvents.addListener('CONFERENCE_LEFT', (data) => {
      console.log('CONFERENCE_LEFT');
    });
    setTimeout(() => {
      JitsiMeet.call('https://meet.jit.si/pepe');
    }, 1000);
  }
```

The only change to your code is the url (and the function name)

The FATAL error that shows android studio is:

```
E/ReactNativeJS: RNFirebase core module was not found natively on Android, ensure you have correctly added the RNFirebase and Firebase gradle dependencies to your `android/app/build.gradle` file.
    
     See http://invertase.link/android for the android setup guide.
E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.eternity.nulesinfo, PID: 10629
    com.facebook.react.common.JavascriptException: RNFirebase core module was not found natively on Android, ensure you have correctly added the RNFirebase and Firebase gradle dependencies to your `android/app/build.gradle` file.
    
     See http://invertase.link/android for the android setup guide., stack:
    t@645:640
    <unknown>@645:2187
    v@2:1496
    d@2:949
    o@2:435
    <unknown>@644:127
    v@2:1496
    d@2:949
    o@2:435
    <unknown>@641:206
    v@2:1496
    d@2:949
    o@2:435
    <unknown>@466:354
    v@2:1496
    d@2:949
    o@2:435
    <unknown>@339:229
    v@2:1496
    d@2:949
    o@2:435
    <unknown>@11:58
    v@2:1496
    d@2:879
    o@2:435
    global code@884:4
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:203)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:761)
```
The exact error place is in JitsiMeetView.class file, line 199

`this.reactRootView.startReactApplication(ReactInstanceManagerHolder.getReactInstanceManager(), "App", props);`

Any idea?, thanks in advance for your help (and this plugin too)

**Comment by RicardoBer** [comment]
More clues,

I see that plugin uses 1.16.0 version of jitsi maven repository, and they have 1.21.0 now.
If you go to [](https://github.com/jitsi/jitsi-meet/tree/master/android/app) it shows that the update 9 days ago was for "rn: add Firebase integration", just the cause of the problem I found.

I changed the verdión in  build.gradle of plugin react-native-jitsi-meet from 

implementation ('org.jitsi.react:jitsi-meet-sdk:1.16+') {

to

implementation ('org.jitsi.react:jitsi-meet-sdk:1.21+') {

But I can't compile, I think this would be solved with an sdk update

**Comment by skrafft** [comment]
I checked the commit that is adding Firebase integration to Jitsi but I don't think this is related to your problem. I'll try to reproduce it on my side and will keep you updated.

**Comment by RicardoBer** [comment]
Hello, first of all many thanks for your fast attention.

I use a local rest (not published yet), so, I will clean the app and try to reproduce the error more clear to send you a version you can test.

I will write soon

**Comment by RicardoBer** [comment]
Hello again,

The error is related to react-native-firebase.

If seems that they try to initialize all apps "in app".

**Comment by RicardoBer** [comment]
Hello again, I create two projects, one with only your plugin and jitsi works perfect, your plugin is easy to use man.

On the other side I add React Native Firebase plugin, compile from command line and from Android Studio and produce the error showed on this issue.

I zipped the projects and upload to own server, how can I send you its links?

**Comment by RicardoBer** [comment]
Once again,

Finally I can make it work.

Your plugin is very ease to use, thanks for that.

I find that Firebase plugin is not started well when start jitsi activity, fail some dependencies, I change only javascript code on their dist folder to avoid exceptions and errors when initialize it with jitsi activity, I create a merely empty object.

Finally show a new error from react native on starting runnable, I found a runnable instance from app but not for jitsi activity, I detected that there was a problem with bundle.

I delete and rebuild the bundle some times with no success, finally clean all the caches and plugins (includind gradle ones) and it works now.

I didn't go deeper in the problem root, but this was the conjuntion of at least this two problems,

Many thanks for your work.

**Comment by saadqbal** [comment]
Hi @RicardoBer,
Can you share how you solved the issue. I have changed the constructor in firebase.js but it gives another error.

**Comment by RicardoBer** [comment]
I can make it work after many weeks, it's no joke, many weeks. After make a lot of changes on many code places and change xcode config, but I can't reproduce the solution.

I can build and make the app works but I can't make it again. The project is ended (lost money and time with it) and I can't make more test, Sorry.

The only conclusion I have is that it is not related to firebase problem, it is related to xcode and react native problem, but arrise on extrange sites.

Sorry, if I have more time to test and find the solution I publish it here.

**Comment by bjkuncoro** [comment]
Hi, @skrafft  i still have a problem for this issue. there is any update for this issue? i use RN 0.61.5, my app crash when  start jitsiMeet.call(uri,userInfo)

**Comment by sampathatom** [comment]
I am having the same issue when integrating this into our app. Any ideas on how to fix this?
