### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by riobijanero** [skrafft/react-native-jitsi-meet#2]
Hello, I just tried using this library.
After following the steps for installing it and importing it in the main RN component, it still shows me this error message when i build the project
can you help out?
<img width="246" alt="bildschirmfoto 2018-09-12 um 11 38 08" src="https://user-images.githubusercontent.com/5263167/45416981-65d08180-b681-11e8-88bb-dc610518aaad.png">

**Comment by riobijanero** [comment]
i tried to follow the instructions, 
had problems at
4-2.) add libRCTWebRTC.a
the file doesn't show up so I can add it.

**Comment by skrafft** [comment]
Hi,
Sorry, there's an error in the documentation. 4-2.) should be add libRNJitsiMeet.a
Can try ?

**Comment by skrafft** [comment]
@riobijanero I've updated the README with feedback from issue #1. 

For iOS, I've added sections 1.5 and 4.6
For android, I've updated sections 4 and 7

Hope this will help you

**Comment by riobijanero** [comment]
Hello skrafft,
thank you, it works now!

I do get these warnings though
![img_1805](https://user-images.githubusercontent.com/5263167/45433364-4864dd00-b6ac-11e8-9cdf-647ce4e02071.PNG)
