### ISSUE TITLE
Bad implementation in latest version using jitsi 1.21

### ISSUE THREAD

**Issue by RicardoBer** [skrafft/react-native-jitsi-meet#20]
There is a problem, at least in android 

Jitsi people encapsulate main object in another way (differs from 1.16 version).

When use your plugin latest version and run on studio shows:

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.eternity.nulesinfo/com.reactnativejitsimeet.JitsiMeetNavigatorActivity}: java.lang.RuntimeException: Enclosing Activity must implement JitsiMeetActivityInterface`

I just uninstall older one and reinstall this version.

Runing on Android Studio fires this error.

I think this can help:

[jitsi/jitsi-meet#3698](https://github.com/jitsi/jitsi-meet/issues/3698)

**Comment by skrafft** [comment]
Can you confirm that latest master commit fixes the problem ?

**Comment by RicardoBer** [comment]
I have a surprising problem

In cmd I execute
> npm uninstall react-native-jitsi-meet 
then
> npm install react-native-jitsi-meet --save

If i open package.json I see that the react-native-jitsi-meet version is the 1.1.0, but when I go to android code folder I saw old code in JitsiMeetNavigatorActivity.java for example.

```
...
public class JitsiMeetNavigatorActivity extends AppCompatActivity implements JitsiMeetViewListener{
...
```

I must donwload the zip of master repo and manual override ios and android folder.

Any way, when I override the android and ios folders I can compile and run tha app.

Now it goes into room, no exception now, but it stays in black background and no ask for login.

I try to ask to jiste people what can be the reason.

Thanks, I will put here the response.

**Comment by diegolmello** [comment]
@skrafft I think npm is outdated.

This way may work, @RicardoBer
```sh
npm i --save skrafft/react-native-jitsi-meet#master
```
