### ISSUE TITLE
Android apk bundleRelease error

### ISSUE THREAD

**Issue by mustafaefdal** [skrafft/react-native-jitsi-meet#200]
hey everyone,

There is no problem between my files and my react-native versions but when i trying to create an apk file, React-native-Jitsi-meet library prevents me from creating an apk file. 

![unknown](https://user-images.githubusercontent.com/45698331/89777643-bfaf7f80-db14-11ea-88fe-a4043547b30b.png)

on the error screen it suggests adding to the androidmanifest.xml file, but the code it mentioned is already in the androidmanifest.xml file

what can i do to solve this problem?

**Comment by rrymm** [comment]
Hi,

In your AndroidManifest.xml add:
xmlns:tools="http://schemas.android.com/tools
and
tools:replace="android:allowBackup"

as per suggestion on the screenshot.

 <application
      **xmlns:tools="http://schemas.android.com/tools"**
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      **android:allowBackup="false"**
      tools:replace="android:allowBackup"
      android:theme="@style/AppTheme">
      <activity

**Comment by mustafaefdal** [comment]
hey,

thank you for your help. i added what you said to my codes. but
unfortunately, a new error has occurred.

[image: unknown.png]

i searched the internet for finding any solution this problem. but
solutions i found were useless. what can i do for this error?

thank you for kindly help :)

Mustafa Efdal

rrymm <notifications@github.com>, 11 Ağu 2020 Sal, 06:05 tarihinde şunu
yazdı:

**Comment by arun111** [comment]
Hi Bro,
I am also facing same issue. How did you fixed it?
