### ISSUE TITLE
Module Not Found 'error: cannot find symbol 'import com.reactnativejitsimeet.JitsiMeetPackage;'

### ISSUE THREAD

**Issue by Jeeva0104** [skrafft/react-native-jitsi-meet#212]
Hi, I am trying to install the Jitsi and after installing and trying of run-native-run-android it shows me the following error.

![image](https://user-images.githubusercontent.com/47843536/92312017-80bcfe80-efda-11ea-9cec-97d233d5d0ca.png)
![image](https://user-images.githubusercontent.com/47843536/92312036-b19d3380-efda-11ea-8b4f-e2bfaf80f36e.png)

**RN Version:0.63.2**
**react-native-jitsi-meet:2.1.1**

**Comment by nikilarigela** [comment]
hi did you find the solution

**Comment by Jeeva0104** [comment]
Yes I found the solution thank you
