### ISSUE TITLE
Important! Problem on React native Android version 10 Cordially.

### ISSUE THREAD

**Issue by Marinaarimany** [skrafft/react-native-jitsi-meet#213]
Hello, I am currently using the react-native-jitsi-meet library in my project. However, I am experiencing an error with this on my Android phone version 10.0 (Huawei p20 pro). When I want to join a video call as administrator, a pop-up is displayed every minute with this error message: “Cannot initiate video call when you are already on a call”, obviously I don't have no other call at the same time. When I quit the app, this pop-up still appears and I cannot call or send voicemail messages with my phone. I have to restart this one. It has been several days that I try to find a solution to this problem. If you can help me please thank you very much.

Cordially.

**Comment by progressify** [comment]
I don't understand your language, but I also have a problem with Huawei with Kirin CPU.
If you try to explain your problem in English probably I can understand if we have the same problem :)

**Comment by Marinaarimany** [comment]
@progressify 
I solved it by disabling the callkit and updating the sdk ;)
