### ISSUE TITLE
Jitsi-Meet meeting lists and starting meeting

### ISSUE THREAD

**Issue by mustafaefdal1** [skrafft/react-native-jitsi-meet#219]
Hello,
I developed a jitsi meet mobile app with react native. however, I can only log in conferences that have already been opened.
I want to open new conferences and I want to see the list of meetings that exist on my home page.

How can it be possible?

**Comment by skrafft** [comment]
Unfortunately, the library does not have this feature at the moment because Jitsi Meet SDK does not include it. If you are running your own server, you probably can do it on the server side via an api but I did not find any documentation on this.
