### ISSUE TITLE
App is closing automatically?

### ISSUE THREAD

**Issue by Tharinducs** [skrafft/react-native-jitsi-meet#227]
In my react native application I am using jitsi react-native wrapper. My code looks like this.

`import React, {Component, useEffect} from 'react';
import JitsiMeet, {JitsiMeetView} from 'react-native-jitsi-meet';

const JitsiVideo = () => {
  useEffect(() => {
    setTimeout(() => {
      const url = 'https://meet.jit.si/MagneticNichesBlameTruly';
      const userInfo = {
        displayName: 'Tharaka',
        email: 'tharindu@example.com',
        avatar: 'https:/gravatar.com/avatar/abc123',
      };
      JitsiMeet.call(url);
      /* Você também pode usar o JitsiMeet.audioCall (url) para chamadas apenas de áudio */
      /* Você pode terminar programaticamente a chamada com JitsiMeet.endCall () */
    }, 1000);
  }, []);

  useEffect(() => {
    return () => {
      JitsiMeet.endCall();
    };
  });

  function onConferenceTerminated(nativeEvent) {
    /* Conference terminated event */
    console.log(nativeEvent);
  }

  function onConferenceJoined(nativeEvent) {
    /* Conference joined event */
    console.log(nativeEvent);
  }

  function onConferenceWillJoin(nativeEvent) {
    /* Conference will join event */
    console.log(nativeEvent);
  }
  return (
    <JitsiMeetView
      onConferenceTerminated={(e) => onConferenceTerminated(e)}
      onConferenceJoined={(e) => onConferenceJoined(e)}
      onConferenceWillJoin={(e) => onConferenceWillJoin(e)}
      style={{
        flex: 1,
        height: '100%',
        width: '100%',
      }}
    />
  );
};

export default JitsiVideo;`

I am navigating to this component when the user clicks on a button. when navigating to this component it is showing a black background and when this code is executed JitsiMeet.call(URL); it is closing my app without showing any error. I tried a lot to find out a solution for this one but I was unable to do so. If someone can help me out with this one it is really great. Thank you

**Comment by devcosta** [comment]
Hi, Android or IOS?

Running like a charm on Android and last React Native Version ( 0.63.3 )
https://github.com/devcosta/react-native-jitsi-example

**Comment by V-Kostin** [comment]
@Tharinducs It`s sound like some rerender after change state, please learn to react hooks(useEffect), the problem in 

useEffect(() => {
return () => {
JitsiMeet.endCall();
};
});

u must add next argument, "[]"

useEffect(() => {
return () => {
JitsiMeet.endCall();
};
}, []);

**Comment by kssimba** [comment]
Hi
I have a similar issue.
But my app crashes as soon as I launch it.
I added react-native-jitsi-meet into my existing react native app.
I followed the instructions https://github.com/skrafft/react-native-jitsi-meet.
How can I solve this issue?
Thanks.

**Comment by arun111** [comment]
Hi,
I am also facing. same issue like when app crashes as soon as i lunch it

**Comment by fr0xy** [comment]
I had the same probleme, You may have forgoten ios config part of the tutorial ( add permissions in info.plist )

**Comment by Tharinducs** [comment]
> Hi, Android or IOS?
> 
> Running like a charm on Android, React Native Version ( 0.63.3 )
> https://github.com/devcosta/react-native-jitsi-example

Android. It was fine when running the sample but when I try to open it through my app navigation it was clashed

**Comment by Tharinducs** [comment]
The solution for my issue was I had put the wrong minsdk version. So when I put it to 24 it was worked finly
