### ISSUE TITLE
Error when create apk debug

### ISSUE THREAD

**Issue by farhanisml** [skrafft/react-native-jitsi-meet#229]
I was running the example app, and it work. But when i try build the apk debug using :

```
react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

cd android

./gradlew assembleDebug
```

theres an error like this on the app :

![2020-11-02 10 30 57](https://user-images.githubusercontent.com/73807902/97827337-9149d680-1cf6-11eb-990d-d8df0150dae4.jpg)

Can someone help me

**Comment by riyas145** [comment]
is that fixed @farhun
