### ISSUE TITLE
How to remove invite people and other extra icon/options from meeting page?

### ISSUE THREAD

**Issue by maheshmbm** [skrafft/react-native-jitsi-meet#23]
I have implemented react-native-jitsi-meet for my app & its working perfectly. But I need to remove extra action such as invite people , lock room, start showing subtitle, start recording. I did not find any way in node modules. Please help me out. 
![IMG_1390](https://user-images.githubusercontent.com/48468577/54180852-b0ad4380-44c2-11e9-8839-bee91c064cc3.PNG)

**Comment by skrafft** [comment]
@maheshmbm, you have two options to do it:

1. The clean one: Fork Jitsi Meet to change the source code and add custom flags to display or not the menu buttons.

1. The dirty one: Remove the menu buttons from the minified jitsi meet javascript source code when compiling your app

Due to time constraints, in the app I made, I chose option 2 and built a few scripts based on sed to remove unwanted buttons.

Typically, this is the code I added to a build script after ios compilation:

```
sed -i "" 's/key:"render",value:function(){var e=this.props;e._addPeopleEnabled,e._dialOutEnabled/key:"render",value:function(){return null;var e=this.props;e._addPeopleEnabled,e._dialOutEnabled/g' ../node_modules/react-native-jitsi-meet/ios/JitsiMeet.framework/main.jsbundle
sed -i "" 's/o.default.createElement(d.RoomLockButton,e),o.default.createElement(f.RecordButton,e),o.default.createElement(f.LiveStreamButton,e),//g' ../node_modules/react-native-jitsi-meet/ios/JitsiMeet.framework/main.jsbundle
```

**Comment by maheshmbm** [comment]
**@skrafft** Thanks. But I could not figure out the location of the files need to change in **react-native-jitsi-meet.** I tried with
1) add the given script code in main.jsbundle of my project.
2) By commenting import package in JitsiMeet.h of JitsiMeet.framework.
3) Traversed through all files of **react-native-jitsi-meet**  node module, but did not got solution.

**Comment by jean-ben-guigui** [comment]
Hello,

> 2. The dirty one: Remove the menu buttons from the minified jitsi meet javascript source code when compiling your app

@skrafft, is there such a solution for android?

**Comment by anshumanburman** [comment]
@maheshmbm have you found any solution for this issue? if yes please tell me.

**Comment by letaptravek** [comment]
> @maheshmbm, you have two options to do it:
> 
> 1. The clean one: Fork Jitsi Meet to change the source code and add custom flags to display or not the menu buttons.
> 2. The dirty one: Remove the menu buttons from the minified jitsi meet javascript source code when compiling your app
> 
> Due to time constraints, in the app I made, I chose option 2 and built a few scripts based on sed to remove unwanted buttons.
> 
> Typically, this is the code I added to a build script after ios compilation:
> 
> ```
> sed -i "" 's/key:"render",value:function(){var e=this.props;e._addPeopleEnabled,e._dialOutEnabled/key:"render",value:function(){return null;var e=this.props;e._addPeopleEnabled,e._dialOutEnabled/g' ../node_modules/react-native-jitsi-meet/ios/JitsiMeet.framework/main.jsbundle
> sed -i "" 's/o.default.createElement(d.RoomLockButton,e),o.default.createElement(f.RecordButton,e),o.default.createElement(f.LiveStreamButton,e),//g' ../node_modules/react-native-jitsi-meet/ios/JitsiMeet.framework/main.jsbundle
> ```

@skrafft , Can you please provide the 2nd solution for android. Where do I add this script for android.? 
Thanks

**Comment by BoumBam** [comment]
I'm also looking for any solution.

How to solve this issue ?
