### ISSUE TITLE
React native app build failed with react native jitsi meet on android?

### ISSUE THREAD

**Issue by Tharinducs** [skrafft/react-native-jitsi-meet#233]
When trying to build a react native app it gives me this error. Program type already present: com.reactnativecommunity.netinfo.BroadcastReceiverConnectivityReceiver$1 then I add this one to Gradle.  `exclude group: 'com.facebook.react',module:'react-native-community_netinfo'` then it makes app crash after build

**Comment by raza2022** [comment]
@Tharinducs how did you solved this, I am facing the same issue, can you please share some code or hint to overcome it?
