### ISSUE TITLE
App clash in production build?

### ISSUE THREAD

**Issue by Tharinducs** [skrafft/react-native-jitsi-meet#234]
I am using jitisi meet react-native wrapper with react-navigation. After building the production build it clashes the app. But works fine in the emulator or real device with development mode. I do not know where I have done wrong.  Can someone give me a solution to this one. I remove all the parts I put to integrate with jitsi and put a build again it was works fine

**Comment by agustinmejia** [comment]
I have the same problem 3 days ago, the app closes without error in the  release version.

`
"dependencies": {
"@react-navigation/native": "^5.1.7",
"@react-navigation/stack": "^5.2.14",
"react": "16.13.1",
 "react-native": "0.63.3",
"react-native-jitsi-meet": "^2.1.1",
}

`

**Comment by agustinmejia** [comment]
https://github.com/skrafft/react-native-jitsi-meet/issues/87#issuecomment-564886538

**Comment by Tharinducs** [comment]
```

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false
```

The issue for me as I have put enableProguardInReleaseBuilds to true. For anyone facing this issue.
