### ISSUE TITLE
app(android) is crashing when hermes is disabled for the custom designs .aar file and works fine when is it is enabled 

### ISSUE THREAD

**Issue by manpreetsingh3215** [skrafft/react-native-jitsi-meet#239]
I need to disable the hermes as is giving so many issues in the app (like this one https://github.com/facebook/hermes/issues/386  ). is there a custom way to disable the hermes in the module ? below are the screenshots of the build.gradle file of module , app and android 
<img width="799" alt="Screenshot 2020-12-16 at 2 12 01 PM" src="https://user-images.githubusercontent.com/42042301/102325061-b34aa000-3fa8-11eb-9b14-bd3a71a3d502.png">
<img width="722" alt="Screenshot 2020-12-16 at 2 11 01 PM" src="https://user-images.githubusercontent.com/42042301/102325067-b6de2700-3fa8-11eb-8df6-bb185f26aaaa.png">
<img width="844" alt="Screenshot 2020-12-16 at 2 10 45 PM" src="https://user-images.githubusercontent.com/42042301/102325071-b80f5400-3fa8-11eb-824c-989f1f62013c.png">

**Comment by deepakverma4** [comment]
@manpreetsingh3215  was you able to run jitsi without hermes?
