### ISSUE TITLE
dyld: Symbol not found: _$SBOWV, Referenced from JitsiMeet, Expected in libswiftCore.dylib

### ISSUE THREAD

**Issue by RicardoBer** [skrafft/react-native-jitsi-meet#24]
Using XCode 9.4.1 (9F2000) and deplay target 9.0 throws this error just on start

![image](https://user-images.githubusercontent.com/14173576/54289030-b9784500-45a8-11e9-8a07-8b60db3e45b4.png)

I follow all steps on iOS manual installation.

It seems related to a swift version problem as I read on other pluging docs.

**Comment by skrafft** [comment]
@RicardoBer, from v1.0.6, you can only compile this lib with XCode 10. Can you give it a try with v1.0.5 ?

**Comment by RicardoBer** [comment]
Thanks again for your fast response.

I tried updating xcode to 10.1 (you know apple push us a bit) and it works.

Many thanks.
