### ISSUE TITLE
No video and audio on celular data

### ISSUE THREAD

**Issue by foneazmi** [skrafft/react-native-jitsi-meet#240]
i had problem, work well using wifi, 
but get problem if using celular data.
no audio and no video

![2020-12-17 15 13 58](https://user-images.githubusercontent.com/26783512/102461146-9383ac80-407a-11eb-9e9c-17cb2689e91e.jpg)

![2020-12-17 15 13 37](https://user-images.githubusercontent.com/26783512/102461118-88c91780-407a-11eb-946e-91ceb6d457e2.jpg)

    "react-native": "0.63.3",
    "react-native-jitsi-meet": "^2.1.1",

**Comment by jbg** [comment]
This is unlikely to be an issue in this library. Are you still experiencing this problem?

**Comment by foneazmi** [comment]
[solved] server problem
