### ISSUE TITLE
How to automatically leave when user left the conversation in react-native application

### ISSUE THREAD

**Issue by G10dRafaFan** [skrafft/react-native-jitsi-meet#249]
Hi, I am using react-native-jitsi-meet in my react-native application. I want to implement the following feature
1)Caller create new Conference Meeting room and join the room.
2)If partner left room due to internet connection what to do to automatically leave the room.
Is there any way to do this .
"react": "16.8.6",
"react-native": "0.63.4",
"react-native-jitsi-meet": "^2.1.1",
Looking forward to the community help. Thank you very much.

**Comment by vijayakm** [comment]
Hi

may I ask you how have you solved it ?

**Comment by G10dRafaFan** [comment]
@vijayakm onParticipantLeft is fired when any user has left the call, so you can call that event and add your functionality.
