### ISSUE TITLE
How to make my custom SDK based on 3.0 version works?

### ISSUE THREAD

**Issue by zhuyuan2016** [skrafft/react-native-jitsi-meet#257]
Hi, I face a issue.
I use the lastet version react-native-jitsi-meet in my project, as you know,it use the 2.x version now,but I make a custom SDK based on 3.0 version,it dosen't works on ios,cause the official sdk name become JitsiMeetSDK from tag 4601.
So,how can I make it work again?What change should I do?

**Comment by Sylordster** [comment]
-#import <JitsiMeet/JitsiMeet.h>
+@import JitsiMeetSDK;

-#import <JitsiMeet/JitsiMeetViewDelegate.h>
+@import JitsiMeetSDK;

-#import <JitsiMeet/JitsiMeetUserInfo.h>
+@import JitsiMeetSDK;

It's work for me.

**Comment by techiespace** [comment]
@Sylordster thanks for your answer after this change I was able to get the SDK working. However toggle camera and microphone on/off buttons are not working for me. When the meeting starts mic and camera is on. When I click on the buttons it turns off as expected but I cannot turn it back on again.
When the meeting loads I get this error:
```
2021-07-16 13:38:20.306870+0530 streamstyle[4391:1839825] [JitsiMeetSDK] FATAL ERROR: RCTFatalException: Unhandled JS Exception: TypeError: undefined is not an object (evaluating 't.callUUID')
```

After tuning mic off:
```
2021-07-16 13:40:18.400177+0530 streamstyle[4391:1840508] [JitsiMeetSDK] [modules/RTC/JitsiLocalTrack.js] Mute LocalTrack[1,audio]: true
```
There are no logs when I try to turn it back on. 
SDK version: 3.6.0

**Comment by Sylordster** [comment]
I used the version 3.2 SKD

**Comment by riyas145** [comment]
@Sylordster How to use custom sdk for new react native version?
