### ISSUE TITLE
embedding jitsi meet latest version

### ISSUE THREAD

**Issue by Frindecent** [skrafft/react-native-jitsi-meet#26]
Hi there,

Thank you for your contribution.

Jitsi meet has changed their api method for calling and and building room.

i have tried to use your wrapper with the latest jitsi meet version. since they have changed their api method to join and build the room. i was able to make some changes and joining the room was possible and jitsi meet was initialized properly. but the overflows like menu button or chat are not displaying on the screen. the buttons seems to work but they do not display. do you have any idea about that? or would you be releasing new version of your library working well with jitsi meet latest api

**Comment by saadqbal** [comment]
@Frindecent I am struggling with the making the new api to work. Can you share your code?

**Comment by Frindecent** [comment]
@saadqbal 
i am using it for android only. do you want for android only..? 
also make sure that maven url for jitsi meet is in local repository and not the other hosted https url.

**Comment by ngoctan95** [comment]
Hi @Frindecent , you set it up properly. You have faced this issue yet? 
```
 com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'streamURL' of a view managed by: RTCVideoView
```
If you catched that before, could you share to me something to fix that? Thanks.

**Comment by skrafft** [comment]
@Frindecent,

Can you try latest version: 1.2.0 ? It should solve your problems.

**Comment by skrafft** [comment]
Closing inactive issue
