### ISSUE TITLE
Jitsi with callkeep

### ISSUE THREAD

**Issue by vijayakm** [skrafft/react-native-jitsi-meet#260]
Hi,

Is it possible to use react-native-callkeep (or iOS callkit) with Jitsi to have better notification ?

**Comment by vijayakm** [comment]
I found the solution

**Comment by deepakverma4** [comment]
@vijayakm  can you please share the solution here?

**Comment by vijayakm** [comment]
With Android use this method to launch the notification :  

```
   const UUID = 'here random uuid'
   const name = ' calling user name'

   RNCallKeep.displayIncomingCall(UUID,` name );
```

Then, when you click on 'answer' button use this callback : 

```
RNCallKeep.addEventListener('answerCall', () => {
      navigation.navigate('ToYourJitsiPanel');
});

```
