### ISSUE TITLE
Stop Jitsi creating call log in phone.

### ISSUE THREAD

**Issue by Zurdge** [skrafft/react-native-jitsi-meet#263]
Hi folks,
Does Jitsi always have to create a log in the phones call history? It might look a little odd/questionable for less tech-savvy people if they suddenly start getting random numbers appearing in their call history.
![Screenshot_20210331_084716](https://user-images.githubusercontent.com/10058489/113109381-dae31280-91fd-11eb-90cf-55d2a2d90def.jpg)

**Comment by Sylordster** [comment]
You need use call-integration.enabled flag

**Comment by Zurdge** [comment]
@Sylordster Thanks for the reply :) 
Jitsi is still very new to me, only been using it a couple of days.
Is the call-integration.enabled flag something I need to do during the self-integration setup?
