### ISSUE TITLE
Reason: image not found

### ISSUE THREAD

**Issue by ngoctan95** [skrafft/react-native-jitsi-meet#27]
Hi @skrafft , thank for building this lib.
I got an issue while embedding lib into my prj. 
Here is log from xCode: 
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /private/var/containers/Bundle/Application/9F2AC667-CB5B-4F5D-8C21-3245281C8010/SNS.app/Frameworks/JitsiMeet.framework/JitsiMeet
  Reason: image not found

How can I resolve this issue? Thanks

**Comment by skrafft** [comment]
Hi @ngoctan95, I had the same problem a while ago. Depending on your XCode version, you have to choose a different version of this lib:
- XCode < 10.2: 1.0.7
- XCode >= 10.2: 1.1.1

Hope this helps

**Comment by ngoctan95** [comment]
Oh really fast. I will give it a try and let you know. Thanks.

**Comment by skrafft** [comment]
I had the same thing, react-native run-ios was successful but in the log, it displays an error about swift not found that is useful to debug. Are you able to paste the build log here ?

**Comment by ngoctan95** [comment]
@skrafft And another thing is: 
"objc[2192]: Class RNVectorIconsManager is implemented in both /private/var/containers/Bundle/Application/07C0B005-6684-40AE-90CA-A562C4596093/SNS.app/Frameworks/JitsiMeet.framework/JitsiMeet (0x101cb4b30) and /var/containers/Bundle/Application/07C0B005-6684-40AE-90CA-A562C4596093/SNS.app/SNS (0x100feba60). One of the two will be used. Which one is undefined." 
objc[2192]: Class RCTFileReaderModule is implemented in both /private/var/containers/Bundle/Application/07C0B005-6684-40AE-90CA-A562C4596093/SNS.app/Frameworks/JitsiMeet.framework/JitsiMeet (0x101cb59e0) and /var/containers/Bundle/Application/07C0B005-6684-40AE-90CA-A562C4596093/SNS.app/SNS (0x100fec2d0). One of the two will be used. Which one is undefined.
objc[2192]: Class RCTBlobManager is implemented in both /private/var/containers/Bundle/Application/07C0B005-6684-40AE-90CA-A562C4596093/SNS.app/Frameworks/JitsiMeet.framework/JitsiMeet (0x101cb5080) and /var/containers/Bundle/Application/07C0B005-6684-40AE-90CA-A562C4596093/SNS.app/SNS (0x100fec320). One of the two will be used. Which one is undefined.
What should I do in this case that two bundles contain these classes ?

**Comment by skrafft** [comment]
@ngoctan95 for the second, I did not find anything I could do but this does not prevent the app from working correctly
For swift version, I don't have anything related to swift in my podfile, this could be a reason though I'm not totally certain why it would cause an error

**Comment by ngoctan95** [comment]
@skrafft , Just removed from linked binary and it works.
