### ISSUE TITLE
Request to be a maintainer

### ISSUE THREAD

**Issue by alexandrtovmach** [skrafft/react-native-jitsi-meet#274]
@skrafft First of all thanks for this great package, it saves me from touching with native part in my projects. I see there are a lot of issues unresolved, and some important PRs just waiting for a long time. I can conclude that you're busy (same as all of us), and open source it's not something in top of priority (at least for majority). But I think we need to continue to support this project, because it's one of the most popular and stable one. I saw that other projects starting re-inventing the wheel, just because of lack of activity here.

Making something from scratch should be the latest scenario, that's why I'd ask to be a maintainer of this repo to help with managing stuff. I'm not promising to resolve everything, but I will try to help with it.

What do you think?

**Comment by levepic** [comment]
Hi Alexandr,

I would join or help you doing this, im going to need this repo for a 
production app both for android and ios. I have a mac, can develop for 
ios too but have no native experience we might need someone for that 
unless there are very simple changes on the native side. I can support 
you either way (joining a new repo or maintaining the original).

Levente

2021.05.10. 17:39 keltezéssel, Alexandr Tovmach írta:

**Comment by alexandrtovmach** [comment]
@skrafft friendly ping

**Comment by skrafft** [comment]
Hi @levepic , @alexandrtovmach. No problem to add you as maintainers. I'll add you to the list of admins. Tell me whenever you think you have a new stable version and I can publish on npm. Remember to follow semantic versioning: https://docs.npmjs.com/about-semantic-versioning for new versions.

@jbg  is already a maintainer.

**Comment by alexandrtovmach** [comment]
Thanks :+1: 
What do you think about setting up CI/CD with auto deploy to NPM?
