### ISSUE TITLE
could not resolve all files for configuration

### ISSUE THREAD

**Issue by Graymark** [skrafft/react-native-jitsi-meet#29]
hi,
i'm new to react native and i try to make an app lie WhatsApp with some communication
I've decided to use a jisti server for this and now i try to implement jitsi in my app thank to your module.
I've installed the library and followed your step but i cant builld the project

the terminal render an error like:
> Task: app:preDebugBuild FAILED
Failure: Build failed with an exception
*What went wrong:
could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find org.webkit:android-jsc:r224109
Required by:
   project :app > project :react-native-jitsi-meet

Can someone help me with this error or had the same output? :)

**Comment by ngoctan95** [comment]
Could you push your more log? I've integrated it so I can help a bit. 
One important thing:Try to update ur system device to latest version.

**Comment by Graymark** [comment]
ok here is my entire log :)
-------------------------------------------
![image](https://user-images.githubusercontent.com/23309661/56036369-ff056a80-5d2c-11e9-83ab-a53ecd924de7.png)
---------------------------------------------
my device android's version is the 5.1
the device tell me that it's the last one available

**Comment by ngoctan95** [comment]
Let put jcenter() in your build.gradle to get it compile

**Comment by Graymark** [comment]
thank you i'll try that :)

**Comment by skrafft** [comment]
@Graymark,

Can you try latest version: 1.2.0 ? It should solve your problems.

**Comment by skrafft** [comment]
Closing inactive issue
