### ISSUE TITLE
How to use react-native-jitsi-meet alongside an already existing webrtc implementation?

### ISSUE THREAD

**Issue by Brumor** [skrafft/react-native-jitsi-meet#291]
I work for a videochat company and we currently have our own implementation of `react-native-webrtc` that we use for videocalls, we would like to switch to jitsi but we need to A/B test it first, therefore having both our implementation of webrtc and jisti along side.

Currently when I add jitsi it crashes the app directly on simulator ("`dyld: Symbol not found: __ZdaPv`"), and crashes when the call is starting on a real device (app freeze). It works fine to uninstall `react-native-webrtc` and use just this library, but that's not what we need.

Do you have any solution or clue that could help me?

**Comment by saranya20-t** [comment]
I'm also facing the same issue. Did you find any solution for that?

**Comment by Brumor** [comment]
Hey @saranya20-t, what I did for iOS was to 
1 - Clone the [jitsi-meet project](https://github.com/jitsi/jitsi-meet)
2 - Go through  this tutorial: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk
3- You get two `.xcframeworks` files: one WebRTC and one for Jitsi, I ignored the WebRTC one and copied the JitsiMeet one to my project [following this guide](https://www.simpleswiftguide.com/how-to-add-xcframework-to-xcode-project/)
4 - Finally I recreated the Module as is being done here, I followed [this guide](https://reactnative.dev/docs/native-modules-ios#setup) and basically copy-pasted the files that are here under the iOS folder to my project and recreated the module.

It works fine on iOS but now I'm struggling with Android instead, if you made some progress, let me know!

**Comment by Brumor** [comment]
Okay so ended up doing the solution above and doing some hack to still use the original `react-native-jitsi-meet`for Android, closing
