### ISSUE TITLE
This Package Updates are not available On npm (version 2.1.2)

### ISSUE THREAD

**Issue by RidaRidss** [skrafft/react-native-jitsi-meet#297]
@skrafft kindly update this package on npm as well.

if user is trying to install this package via npm , it install previous version that is 2.1.1

<img width="1280" alt="Screenshot 2021-08-26 at 6 37 21 PM" src="https://user-images.githubusercontent.com/11027366/130972817-f3f5ce10-84e6-4973-a987-619558df93d7.png">

**Comment by skrafft** [comment]
@RidaRidss published, sorry for the delay
