### ISSUE TITLE
How can i detect other user join my room

### ISSUE THREAD

**Issue by ThanakornNG** [skrafft/react-native-jitsi-meet#30]
I have some problem with detecting user join my room
i've listen to "CONFERENCE_JOINED" event but it trigger only when my phone join the room
not when my computer join the same room

**Comment by skrafft** [comment]
Hi @ThanakornNG, so far, it's not possible with the current Jitsi Meet SDK version, so it's not possible either in react native. I'll keep watching for changes in the SDK and will notify you if available.
