### ISSUE TITLE
Program type already present: com.reactnativecommunity.asyncstorage.AsyncLocalStorageUtil

### ISSUE THREAD

**Issue by Marinaarimany** [skrafft/react-native-jitsi-meet#305]
Hello everyone,

I have an application that uses this library (latest version). When I run it in debug it works by launching the metro server. On the other hand when I want to create an apk I have this error which appears:

AGPBI: {"kind": "error", "text": "Program type already present: com.reactnativecommunity.asyncstorage.AsyncLocalStorageUtil", "sources": [{}], "tool": "D8"}
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives ....

I tried to put exclude group: 'com.facebook.react', module: 'react-native-community-async-storage'
on the library but it doesn't work .. a real nightmare this error. I am using React native 0.63.3.

If anyone can help me please

thanks very much

**Comment by johnhwang87** [comment]
Try npm installing @react-native-async-storage/async-storage, the community one I was using was deprecated. 
And then in your build.gradle file:
exclude group: 'com.facebook.react',module:'react-native-community-async-storage'

**Comment by Marinaarimany** [comment]
@johnhwang87 Thank you, it works I just have an error in itself to correct I do not know if you can help me or not.

 When I run my apk I have this problem: Unable to load script. Make sure you're either running a Metro server (run 'react-native start') or that your bundle 'app.bundle.nameproject' is packaged correctly for release

I know I need to do this line: react-native bundle --platform android --dev false --entry-file index.js --bundle-output android / app / src / main / assets / index.android.bundle - -assets-dest android / app / src / main / res /

But that changes nothing unfortunately.

Thank you :)

**Comment by johnhwang87** [comment]
Hmm, I'm not sure. I use the gradlew commands to build out our apk/aab files. You might find this helpful:
https://reactnative.dev/docs/signed-apk-android

For our project, we use ./gradlew assembleRelease to create our signed apk for testing, and ./gradlew bundleRelease for aab (make sure you are in your android directory when running those commands).
