### ISSUE TITLE
Location of libRNJitsiMeet.a

### ISSUE THREAD

**Issue by zayedelfasa** [skrafft/react-native-jitsi-meet#31]
Hi everyone. I want to thanks to all person who build this project. But, can you guys help me how to get location of "libRNJitsiMeet.a" in "Step 4. Link/Include Necessary Libraries" when i want to manual linking for iOS ? 

I have build for android and running well. But in iOS there is error.

Thanks you!

**Comment by skrafft** [comment]
Hi @zayedelfasa, 

If you have successfully added the RNJitsiMeet.xcodeproj file your project, the libRNJitsiMeet.a line should appear automatically in the list of includable libraries. If you don't have it, it means that the RNJitsiMeet project has not been added correctly to your main project.

**Comment by zayedelfasa** [comment]
thanks for the answer. I can get libRNJitsiMeet.a. But in the next step, i have a problem for "libstdc++.tbd". Where can i get location of "libstdc++.tbd" ? My Xcode version is 10.1. 

I have googling about "libstdc++.tbd". A lot of answer is "libstdc++.tbd" doesn't support. can you help me ?

thank you.

**Comment by zayedelfasa** [comment]
i am finished upgrade xcode to 10.2.1 but there is no libstdc++.tbd file. Can you help me ?

**Comment by skrafft** [comment]
Hi @zayedelfasa,

libstdc++.tbd is present by default on all iOS systems. To add it to your project, go to your project settings, in General, scroll down to "Linked Frameworks and Libraries", click on the + sign, type libs in the search box and you should find libstdc++.tdb in the iOS 12.2 folder.

**Comment by zayedelfasa** [comment]
thank you! its work on my devices! :) Thank you very much! 👍 nice project
