### ISSUE TITLE
Jitsi bug on iOS emulator with RN 0.66.4

### ISSUE THREAD

**Issue by jean-ben-guigui** [skrafft/react-native-jitsi-meet#348]
Hi,

I have created a project using "npx react-native init AwesomeProject --version 0.66.4". The project launches and I have no problem.
Then I added react-native-jitsi-meet in the project. I used the CallVideo component from the readMe and I added it to App.js.
I encountered a first problem due to the fact that the `const blacklist = require('metro-config/src/defaults/blacklist');` from the readMe no longer exists and needs to be changed to `const exclusionList = require('metro-config/src/defaults/exclusionList');`. That being done, I was able to run my app on a physical device (Iphone XR - iOS 15.02) I have no problem, everything runs smoothly.
However when running the project on an emulator (iphone 13 - iOS 15.2 | iphone 12 - iOS 14.5) I have the following problems:
Using the podfile as is, the build fails with the following error:

```
Undefined symbol: _OBJC_CLASS_$_FlipperKitNetworkPlugin
Undefined symbol: _OBJC_CLASS_$_SKIOSNetworkAdapter
Undefined symbol: _OBJC_CLASS_$_FlipperKitReactPlugin
Undefined symbol: _OBJC_CLASS_$_FKUserDefaultsPlugin
Undefined symbol: _OBJC_CLASS_$_FlipperKitLayoutPlugin
Undefined symbol: _OBJC_CLASS_$_SKDescriptorMapper
Undefined symbol: _OBJC_CLASS_$_FlipperClient
```
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/15104156/153247602-1bb68693-a8cf-4855-afff-53a974b95017.png)

So I tried commenting `use_flipper!()` in the podfile. The app builds but then crashes almost instantly with the following error:
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/15104156/153248282-25b4fffd-b499-4731-be7c-b91460238065.png)

Maybe I am doing something wrong or there is a compatibility problem with RN 0.66.4?

Any help will be highly appreciated 👍

**Comment by jean-ben-guigui** [comment]
Thanks for the answer @VitDev17. Could you share how you came to that conclusion?

**Comment by VitDev17** [comment]
Hi @jean-ben-guigui , i basically started a fresh project from scratch and started testing versions of RN and React. I found out that my app work with RN 0.63.4 and React v17.0.2. I also just find out that with ios 15.2 the jitsi meet doesn't work at all and crashed after splashscreen.
So far i managed to make it run only on iphone 8 with iOS 13.7. But you too understand that is not optimal.

**Comment by jean-ben-guigui** [comment]
Thanks for sharing your results with me. @skrafft could you tell us which react native version you work with, so that we can be sure to work in a proper environment?

**Comment by jean-ben-guigui** [comment]
Thanks for the quick answer, I managed to make it work on iOS emulator by commenting `use_flipper!()` in the podfile and by adding arm64 in the excluded architectures of the Pods project:
<img width="1293" alt="Screenshot 2022-02-11 at 11 40 24" src="https://user-images.githubusercontent.com/15104156/153577678-f86d5701-487b-4bbe-9d0f-19f49181b41d.png">

The fact that I am running a M1 Mac probably has something to do with these problems.

Now I am struggling with android as the buttons don't work as stated in #331 . Are you using android with react native 0.65.1 @skrafft ? If you do, have you been able to fix this issue?
Thanks again for the help, I appreciate it.

**Comment by skrafft** [comment]
For #331, we were able to fix the issue. Disclaimer: the fix is very dirty.

You need to replace some faulty code in the original jitsi meet library:

This is the code we use is this one: sed -i "" 's/l.playTouchSound()//g' index.android.bundle

**Comment by jean-ben-guigui** [comment]
Okay, sounds great.
I never played with files in the build directory though. Could you explain how I should use that command? 

I tried to modify the package.json to add a script `"android": "npx react-native run-android && sed -i \"\" 's/l.playTouchSound()//g' android/app/build/intermediates/merged_assets/debug/out/index.android.bundle",` and then run `npm run android `. If I check in the index.android.bundle,` l.playTouchSound()` has been deleted but the buttons still don't work.

**Comment by skrafft** [comment]
Hi, it cannot be done via npm script because it's too late. It has to be done during the gradle build process.

You need to add the following code at the end of  ```android/app/build.gradle```:

```
gradle.projectsEvaluated {
    // Grab all build types and product flavors
    def buildTypes = android.buildTypes.collect { type -> type.name }
    def productFlavors = android.productFlavors.collect { flavor -> flavor.name }

    // When no product flavors defined, use empty
    if (!productFlavors) productFlavors.add('')

    productFlavors.each { productFlavorName ->
        buildTypes.each { buildTypeName ->
            // Create variant and target names
            def flavorNameCapitalized = "${productFlavorName.capitalize()}"
            def buildNameCapitalized = "${buildTypeName.capitalize()}"
            def targetName = "${flavorNameCapitalized}${buildNameCapitalized}"
            def targetPath = productFlavorName ?
                    "${productFlavorName}/${buildTypeName}" :
                    "${buildTypeName}"

            // Bundle task name for variant
            def cleanJsAndAssetsTaskName = "clean${targetName}JsAndAssets"

            def currentBundleTask = tasks.create(
                    name: cleanJsAndAssetsTaskName,
                    type: Exec) {
                group = "react"
                description = "clean JS and assets for ${targetName}."

                workingDir "${projectDir}/../.."
                commandLine "bash","-c","${projectDir}/../../clean.sh"
            }

            // Hook bundle${productFlavor}${buildType}JsAndAssets into the android build process
            currentBundleTask.dependsOn("merge${targetName}Assets")

            runBefore("process${flavorNameCapitalized}Armeabi-v7a${buildNameCapitalized}Resources", currentBundleTask)
            runBefore("process${flavorNameCapitalized}X86${buildNameCapitalized}Resources", currentBundleTask)
            runBefore("processUniversal${targetName}Resources", currentBundleTask)
            runBefore("process${targetName}Resources", currentBundleTask)
            runBefore("dataBindingProcessLayouts${targetName}", currentBundleTask)
        }
    }
}
```
and create a ```clean.sh``` in the root of your project script. This is the content of mine:

```
#!/bin/sh
# Clean jitsi bundle
if [ -f "android/app/build/intermediates/merged_assets/release/mergeReleaseAssets/out/index.android.bundle" ]; then
  echo "Cleaning release merged jitsi lib"
  sed -i "" 's/l.playTouchSound()//g' android/app/build/intermediates/merged_assets/release/mergeReleaseAssets/out/index.android.bundle
fi
if [ -f "android/app/build/intermediates/merged_assets/release/out/index.android.bundle" ]; then
  echo "Cleaning release merged jitsi lib"
  sed -i "" 's/l.playTouchSound()//g' android/app/build/intermediates/merged_assets/release/out/index.android.bundle
fi
if [ -f "android/app/build/intermediates/merged_assets/debug/mergeDebugAssets/out/index.android.bundle" ]; then
  echo "Cleaning debug merged jitsi lib"
  sed -i "" 's/l.playTouchSound()//g' android/app/build/intermediates/merged_assets/debug/mergeDebugAssets/out/index.android.bundle
fi
if [ -f "android/app/build/intermediates/merged_assets/debug/out/index.android.bundle" ]; then
  echo "Cleaning debug merged assets jitsi lib"
  sed -i "" 's/l.playTouchSound()//g' android/app/build/intermediates/merged_assets/debug/out/index.android.bundle
fi
if [ -f "android/app/build/intermediates/assets/debug/index.android.bundle" ]; then
  echo "Cleaning debug jitsi lib"
  sed -i "" 's/l.playTouchSound()//g' android/app/build/intermediates/assets/debug/index.android.bundle
fi
if [ -f "android/app/build/intermediates/assets/release/index.android.bundle" ]; then
  echo "Cleaning release jitsi lib"
  sed -i "" 's/l.playTouchSound()//g' android/app/build/intermediates/assets/release/index.android.bundle
fi
# Clean svg files from drawable folder (svg files are inlined by babel)
echo "Cleaning svg files from drawable folder"
rm -rf android/app/build/generated/res/react/release/drawable-mdpi/*.svg
echo "Done"
```

I hope this helps.

**Comment by jean-ben-guigui** [comment]
Thanks a lot, you're a life saviour. Could you also share the code for the method `runBefore ` used in the script I need to add in `android/app/build.gradle`?
