### ISSUE TITLE
Could not resolve org.jitsi.react:jitsi-meet-sdk:3.7.0

### ISSUE THREAD

**Issue by MahmudHasanMenon** [skrafft/react-native-jitsi-meet#349]
I am using jitsi-meet default SDK  [jitsi-meet](https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_6865l) to run into our react-native-jitsi-meet project. SDK build successfully But i am facing error when running Android project using that SDK.

**react-native : 0.63.4
react-native-jitsi-meet: 2.2.0

OS: macOS Big Sur
Node: 17.4.0**

`Could not resolve org.jitsi.react:jitsi-meet-sdk:3.7.0.
     Required by:
         project :app
         project :app > project :react-native-jitsi-meet`

`Could not get resource 'https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/3.7.0/jitsi-meet-sdk-3.7.0.pom'`
`Could not HEAD 'https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/3.7.0/jitsi-meet-sdk-3.7.0.pom'. Received status code 401 from server: Unauthorized`
       
            
![Screen Shot 2022-02-09 at 6 19 12 pm](https://user-images.githubusercontent.com/29507500/153355336-2d4808d6-db94-4057-9ba2-a519245e1f6c.png)

**Comment by abnormalbbk** [comment]
![image](https://user-images.githubusercontent.com/5323624/153400439-e87f496c-05b2-41e1-ae68-7ab5e6e14802.png)
You need to add 
```
   maven { // <---- Add this block
            url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
        }
```
in your android build.gradle file

**Comment by MahmudHasanMenon** [comment]
> ![image](https://user-images.githubusercontent.com/5323624/153400439-e87f496c-05b2-41e1-ae68-7ab5e6e14802.png) You need to add
> 
> ```
>    maven { // <---- Add this block
>             url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
>         }
> ```
> 
> in your android build.gradle file

if i use
```
 maven { // <---- Add this block
            url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
        }
```
**it works but
 when i use custom SDK build from jitsi-meet code it shows above **error.****
![Screen Shot 2022-02-10 at 6 43 26 pm](https://user-images.githubusercontent.com/29507500/153410902-28f31bfa-4656-4609-b1dc-5d88c7046b29.png)

**Comment by MahmudHasanMenon** [comment]
I fixed the error. I changed to `org.jitsi.react:jitsi-meet-sdk:5.0.0` from `org.jitsi.react:jitsi-meet-sdk:3.7.0` in my `node_modules -> react-native-jitsi-meet -> android -> build.gradle` file.

**Comment by ReejeshPK** [comment]
Possible Network Related Solution : https://stackoverflow.com/a/76246334/7710739
