### ISSUE TITLE
nullable not find

### ISSUE THREAD

**Issue by pranavpandey1998official** [skrafft/react-native-jitsi-meet#36]
/home/pranav/Desktop/myRepo/Rocket.Chat.ReactNative/android/app/src/main/java/chat/rocket/reactnative/MainApplication.java:89: error: cannot find symbol
    protected @Nullable String getBundleAssetName() {
                            ^
  symbol: class Nullable
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 erro

**Comment by skrafft** [comment]
You have to import Nullable at the top of your java file:

```import javax.annotation.Nullable;```
