### ISSUE TITLE
App crashes on Android. Maven url problem.

### ISSUE THREAD

**Issue by dogankablan** [skrafft/react-native-jitsi-meet#369]
Hello everyone.

I'm using jitsi with react native. Everything was normal until 1 week ago. I successfully integrated jitsi into my project and was able to use it. However, 1 week ago I wanted to get a build from my project. I got it successfully on Ios.
On the Android part, there was no change in my normally built application, but it started not getting a successful build.
 I overcame that problem. This time when I got the build the app started crashing.

Then I did a deeper research. I noticed this. When I uninstall Jitsi the application continues to run successfully. But it was working fine even though I used jitsi 1 week ago.
I thought the problem was with jitsi and looked at android side settings in jitsi setup.

Then I did a lot of trial and error methods. And I found this.

My project > android > build.gradle

  expert {
            url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
        }

It looks like this is the line that is causing my project not to build and crashing.

The repo is said to have been updated 8 days ago.
I think this problem occurred after this update.

Anyone having the same problem as me?

**Comment by goff-studio** [comment]
Do not use their master branch. They updated their react-native version to 0.66.x,
that's why you cannot use their master branch anymore.

use
`url "https://github.com/jitsi/jitsi-maven-repository/raw/bc603d897b4328e839d142f03a8365772ca3dbea/releases"` 

instead of 
`url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"`

**Comment by dogankablan** [comment]
> Do not use their master branch. They updated their react-native version to 0.66.x, that's why you cannot use their master branch anymore.
> 
> use `url "https://github.com/jitsi/jitsi-maven-repository/raw/bc603d897b4328e839d142f03a8365772ca3dbea/releases"`
> 
> instead of `url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"`
> 
> I guess, the latest RN version that works with `react-native-jitsi-meet` is RN 0.64.3, using that address should work on 0.64.3

I tried it and it worked for me. Thanks for your interest man.

**Comment by Marinaarimany** [comment]
> Do not use their master branch. They updated their react-native version to 0.66.x, that's why you cannot use their master branch anymore.
> 
> use `url "https://github.com/jitsi/jitsi-maven-repository/raw/bc603d897b4328e839d142f03a8365772ca3dbea/releases"`
> 
> instead of `url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"`
> 
> I guess, the latest RN version that works with `react-native-jitsi-meet` is RN 0.64.3, using that address should work on 0.64.3


Are you using screen sharing on this branch? It doesn't work for me :/

https://github.com/skrafft/react-native-jitsi-meet/issues/380


If you can help me please

Thank you
