### ISSUE TITLE
Clean Install getting Memory Read Failed on iOS device

### ISSUE THREAD

**Issue by mavenman** [skrafft/react-native-jitsi-meet#38]
I am attempting to run the react-native-jitsi-meet sdk wrapper on a clean react-native project that only has the jitsi-meet sdk wrapper added. Build's fine. I verified the dependencies and library inclusions. I am getting the following error:

<img width="1006" alt="xcode_error" src="https://user-images.githubusercontent.com/1912605/60145295-9bb7a000-9793-11e9-9a40-bd00eb30cfc3.png">

This is all I have in the App.js file:
![app_js](https://user-images.githubusercontent.com/1912605/60145354-c30e6d00-9793-11e9-9161-adf1ec8f16b5.png)

When I click the start button the error occurs. Any guidance would be great!

Would there be any issues running this on an iPad with iOS 10? I did set the deployment target to 8.

**Comment by skrafft** [comment]
@mavenman, I tried with my old iPad which has iOS 10 as well and could not reproduce your error. Can you give more information about RN version and plugin version ?

**Comment by mavenman** [comment]
Thank you so much for looking into this: Would it be too much to ask to
have you attempt to load up my generic project? I zipped it and can send
that over. I did leave the node_modules intact as well. Again, builds fine
but generates that error when calling the function to initiate the
conference in RN.


react-native-cli: 2.0.1

react-native: 0.59.9


react-native-jitsi-meet@1.2.0

**Comment by skrafft** [comment]
Hi, I just published V2.0.0 which has been completely re-architectured and is compatible with RN 0.60.

Please read the Readme file as the integration has changed: [README](https://github.com/skrafft/react-native-jitsi-meet/blob/master/README.md)
