### ISSUE TITLE
Version upgrade to Jitsi 6.0

### ISSUE THREAD

**Issue by hawkeye-sama** [skrafft/react-native-jitsi-meet#388]
Is there any chance that this would be upgraded to latest version. Older versions have started to give some issues

**Comment by KolissnikBogdan** [comment]
@skrafft is it even possible to update this package to the latest version of jitsi sdk (6.0.0)?

**Comment by IKTANIM** [comment]
The package not working for android for the latest sdk. Please update the package @skrafft
