### ISSUE TITLE
Ios setup failed

### ISSUE THREAD

**Issue by tusharnetset** [skrafft/react-native-jitsi-meet#39]
Hii 
Can you please help me out with this error in ios 
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib

**Comment by tusharnetset** [comment]
Can Anyone help in this issue ?
I am stuck into this from last two days.

**Comment by skrafft** [comment]
@tusharnetset , which XCode version are you using ?

**Comment by tusharnetset** [comment]
Hi @skrafft 
Thanks for the response.It is working now in device but problem was running it on simulator.

**Comment by tusharnetset** [comment]
I am facing error in android setup with latest react native 0.60.0

> Task :react-native-jitsi-meet:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
17 actionable tasks: 8 executed, 9 up-to-date
/home/netset/Documents/projects/newReactProject/jitsimeet/jitsimeet/node_modules/react-native-jitsi-meet/android/src/main/java/com/reactnativejitsimeet/JitsiMeetNavigatorActivity.java:12: error: cannot find symbol
import android.support.v4.app.FragmentActivity;
                             ^
  symbol:   class FragmentActivity
  location: package android.support.v4.app
/home/netset/Documents/projects/newReactProject/jitsimeet/jitsimeet/node_modules/react-native-jitsi-meet/android/src/main/java/com/reactnativejitsimeet/JitsiMeetNavigatorActivity.java:26: error: cannot find symbol
public class JitsiMeetNavigatorActivity extends FragmentActivity implements JitsiMeetViewListener, JitsiMeetActivityInterface {
                                                ^
  symbol: class FragmentActivity
/home/netset/Documents/projects/newReactProject/jitsimeet/jitsimeet/node_modules/react-native-jitsi-meet/android/src/main/java/com/reactnativejitsimeet/JitsiMeetNavigatorActivity.java:26: error: JitsiMeetNavigatorActivity is not abstract and does not override abstract method shouldShowRequestPermissionRationale(String) in PermissionAwareActivity
public class JitsiMeetNavigatorActivity extends FragmentActivity implements JitsiMeetViewListener, JitsiMeetActivityInterface {

**Comment by djorkaeffalexandre** [comment]
@tusharnetset what you change of the instructions to it run on iOS???

**Comment by skrafft** [comment]
@tusharnetset I did not try to run it with RN 0.60 yet. You might want to stick to 0.59 until I find the time to test and fix the code. If it's already working on your side, I'm happy to accept pull requests.

**Comment by hnrqsss** [comment]
Im facing the same error and till now i cant solve.

'dyld`__abort_with_payload:'

RN: 0.59.3
xCode: 10.1

**Comment by hnrqsss** [comment]
For me solved i installing react-native-webrtc and following the steps of installation from there, so then installed only react-native-jitsi-meet dependencies that not install on step before.

Im in RN: 60 and XCode 10.

Thanks guys

**Comment by grifotv** [comment]
@hnrqsss did you manage to make it work for Android and iOS?

**Comment by hnrqsss** [comment]
> @hnrqsss did you manage to make it work for Android and iOS?

yes i did
