### ISSUE TITLE
Initial directory for React Native SDK

### ISSUE THREAD

**Issue by Aleksandern** [skrafft/react-native-jitsi-meet#396]
It looks like this package is not maintaned.

The Jitse Meet team is working on the initial directory for React Native SDK. That works on iOS only for now but it's in progress.
https://github.com/jitsi/jitsi-meet/pull/11959

**Comment by skrafft** [comment]
We are waiting for it too. We'll deprecate this package as soon as the Official Jitsi SDK is out.
