### ISSUE TITLE
error when building in a project

### ISSUE THREAD

**Issue by riobijanero** [skrafft/react-native-jitsi-meet#4]
Hey skrafft, 
I am getting the following error when integrating the library in an existing iOS-app.
Can it have something to do with react-native vector icons?

`dyld: Symbol not found: _SDWebImageCoderScaleDownLargeImagesKey
 Referenced from: /Users/xxx/Library/Developer/CoreSimulator/Devices/8A86B9B8-BB3F-442F-8B1C-3DFCCEACEA3D/data/Containers/Bundle/Application/6D1163D1-68E6-492A-AC5F-5533B7C18C1A/xxx.app/xxx
 Expected in: /Users/xxx/Library/Developer/CoreSimulator/Devices/8A86B9B8-BB3F-442F-8B1C-3DFCCEACEA3D/data/Containers/Bundle/Application/6D1163D1-68E6-492A-AC5F-5533B7C18C1A/xxx.app/Frameworks/JitsiMeet.framework/JitsiMeet
in /Users/xxx/Library/Developer/CoreSimulator/Devices/8A86B9B8-BB3F-442F-8B1C-3DFCCEACEA3D/data/Containers/Bundle/Application/6D1163D1-68E6-492A-AC5F-5533B7C18C1A/xxx.app/xxx `

**Comment by SeveHo** [comment]
Hi,
I have the same issue and managed to get a step forward by marking **JitsiMeet.framework** and **WebRTC.framework** as optional in **General** > **Linked Frameworks and Libraries**.

But now I get errors for a lot of modules/classes like the both below. It seems like the JitsiMeet framework and my app have overlapping dependencies. Do you have an idea how to resolve this?

objc[12872]: Class RNVectorIconsManager is implemented in both /Users/xxx/Library/Developer/CoreSimulator/Devices/8A86B9B8-BB3F-442F-8B1C-3DFCCEACEA3D/data/Containers/Bundle/Application/BA73EE6D-9678-435B-831C-1486C9F96E35/xxx.app/Frameworks/JitsiMeet.framework/JitsiMeet (0x101a2f3c8) and /Users/xxx/Library/Developer/CoreSimulator/Devices/8A86B9B8-BB3F-442F-8B1C-3DFCCEACEA3D/data/Containers/Bundle/Application/BA73EE6D-9678-435B-831C-1486C9F96E35/xxx.app/xxx (0x100a7b178). One of the two will be used. Which one is undefined.
objc[12872]: Class RNI18n is implemented in both /Users/xxx/Library/Developer/CoreSimulator/Devices/8A86B9B8-BB3F-442F-8B1C-3DFCCEACEA3D/data/Containers/Bundle/Application/BA73EE6D-9678-435B-831C-1486C9F96E35/xxx.app/Frameworks/xxx.framework/xxx (0x101a33338) and /Users/xxx/Library/Developer/CoreSimulator/Devices/8A86B9B8-BB3F-442F-8B1C-3DFCCEACEA3D/data/Containers/Bundle/Application/BA73EE6D-9678-435B-831C-1486C9F96E35/xxx.app/xxx (0x100a7b1c8). One of the two will be used. Which one is undefined.

**Comment by skrafft** [comment]
@SeveHo, I also have the same problem with duplicate libraries. For now, this has not prevented my app to work correctly. I'm still trying to get rid of this message but for now did not manage to succeed.
If you find the solution, I'm interested.
