### ISSUE TITLE
Regarding UI changes: How we can change the design of video call screen.

### ISSUE THREAD

**Issue by jatinderrana** [skrafft/react-native-jitsi-meet#40]
Hi this is not an issue its just a question,
I want to edit design of call screen but i am not able to find it.
Can anybody please help me how i can edit the design or changes in any UI for react native.

**Comment by skrafft** [comment]
It's not possible at the moment. If you want to do it, you have to fork the JitsiMeet project and this project and make the changes. 

A dirty hack could be to update the minified version of jitsi meet with commands like sed but it's very dirty.
