### ISSUE TITLE
can we upgrade jitsi sdk to 6.2.2 

### ISSUE THREAD

**Issue by MinaSamir11** [skrafft/react-native-jitsi-meet#408]
since upgrading to in react native version it got conflicted with other many packages depending on jitsi SDK and some other packages are outdated with other versions, can we start to upgrade to SDK 6.2.2 in android since the project crashed and after along investigation I got a black screen? 

Thank you for your effort and your great lib.

**Comment by skrafft** [comment]
Unfortunately, it's not so easy for android because the Jitsi Team removed a key Java class that we were using. They are planning to release a react native sdk though: https://github.com/jitsi/jitsi-meet/pull/11959. Let's hope it does not take too much time.

**Comment by GleidsonDaniel** [comment]
@skrafft One doubt, with the output of this sdk you would probably drop support for this lib, correct?

**Comment by skrafft** [comment]
That's correct.
