### ISSUE TITLE
Cannot initialize jitsi meet in React-Native android

### ISSUE THREAD

**Issue by BabbaAmine** [skrafft/react-native-jitsi-meet#41]
Hi Skrafft, I installed jitsi meet in react-native and tried to run it on android, but an error occurred when I tried to use this method:
JitsiMeet.initialize ();

![dd](https://user-images.githubusercontent.com/37799517/60772091-f254a080-a0e8-11e9-95d6-d4da1c04e63f.jpg)

**Comment by skrafft** [comment]
Hi @BabbaAmine,

Can you share more information: react native version, jitsi meet version, relevant piece of code ?

Thanks

**Comment by skrafft** [comment]
No answer. Closing this ticket.
