### ISSUE TITLE
Maybe the README needs a change ?

### ISSUE THREAD

**Issue by ThomGrous** [skrafft/react-native-jitsi-meet#42]
Hi !

For some reasons I recently had to reinstall 3 times every library in my application, which includes react-native-jitsi-meet, and I noticed that the README might be missing some instructions which would save time.

Here I put all the code I had to write in order to have react-native-jitsi-meet work in my app (and I am positively sure that it doesn't build without any of it) : 

For Android : 

In android/app/src/main/java/com/appname/MainApplication.java : 

```
import com.reactnativejitsimeet.JitsiMeetPackage; 
import android.support.annotation.Nullable; //Add this line
```

In android/app/src/main/AndroidManifest.xml : 

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:tools="http://schemas.android.com/tools" //Add this line

...

<application
      ...
      tools:replace="android:allowBackup">
```

In android/app/build.gradle : 

```
android{ 
    ...

    packagingOptions {
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/x86/libjsc.so'
        pickFirst 'lib/x86_64/libjsc.so'
        pickFirst 'lib/arm64-v8a/libjsc.so'
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libjsc.so'
    }

```

In android/build.gradle : 

```
        minSdkVersion = 21 //Doesn't work with lower

```

Also for iOS : 
Step 4 --> libstd++.tbd should be libc++.std

Hope that the README will be changed or at least that it will save some time to others

Appart from this, keep up the great work on the library, it's very useful 👍

**Comment by skrafft** [comment]
Hi @ThomGrous, thanks a lot for all the feedback. This helps a lot. I've merged your comments into the main readme.
