### ISSUE TITLE
Does not exist libstdc++.tbd in my Xcode. What to do ?

### ISSUE THREAD

**Issue by hangai247** [skrafft/react-native-jitsi-meet#43]

**Comment by ThomGrous** [comment]
Just answered this : 
#42

**Comment by hangai247** [comment]
Still having this problem. I thought, this was happening because of `libstd++` binary but looks like not.
<img width="1363" alt="Screen Shot 2019-07-10 at 16 35 10" src="https://user-images.githubusercontent.com/33982438/60949861-07bc0b80-a331-11e9-91ce-99a3980f23a3.png">

**Comment by ThomGrous** [comment]
Sorry, I didn't encountered this.

Idk what you've tried to resolve all your problems, but maybe trying to do a fresh install with the tips I provided in my previous comment would do the trick ? 

Sometimes you try so many things to solve your problems that you create more in the end ^^'

**Comment by skrafft** [comment]
@hangai247 your error does not seem to be related to react-native-jitsi-meet. Can you try to reproduce it with only react-native-jitsi-meet in your app ?

**Comment by hangai247** [comment]
> @hangai247 your error does not seem to be related to react-native-jitsi-meet. Can you try to reproduce it with only react-native-jitsi-meet in your app ?

Thank you for your response. Actually I followed and did all of the settings as it mentioned on README.md. and initialized 59.9 react-native application and added only react-native-jitsi-meet. Still having this issue :(
