### ISSUE TITLE
Add 'video' or 'audio' option

### ISSUE THREAD

**Issue by djorkaeffalexandre** [skrafft/react-native-jitsi-meet#45]
We can add an option with 'video' or 'audio' on ```JitsiMeet.call``` or a ```callWithOptions(url, options)```?
If you can't I will go to send a PR. :)

**Comment by skrafft** [comment]
For now, I don't have the time to work on it. If you can send a PR, i'll merge it.

**Comment by skrafft** [comment]
I just pushed this feature to master for iOS. Waiting android sdk for RN 0.60 to release everything at once.

**Comment by djorkaeffalexandre** [comment]
really nice man! I appreciate it!

**Comment by skrafft** [comment]
Hi, I just published V2.0.0 which has been completely re-architectured and is compatible with RN 0.60.

an audioCall function is now provided on top of the call function.

Please read the Readme file as the integration has changed: [README](https://github.com/skrafft/react-native-jitsi-meet/blob/master/README.md)
