### ISSUE TITLE
Update frameworks to use loadUrlObject

### ISSUE THREAD

**Issue by djorkaeffalexandre** [skrafft/react-native-jitsi-meet#46]
If we need to change user Avatar & Name we need to use ```loadUrlObject``` of Jitsi Framework but the version of this library only have ```join``` and ```leave```.

**Comment by skrafft** [comment]
I don't think you can change this with jitsi's current sdk. Only available options are:
- url
- audio muted
- video muted
- audio only
- welcome page enabled

Source: https://github.com/jitsi/jitsi-meet/tree/master/android#jitsimeetconferenceoptions
