### ISSUE TITLE
Picture in Picture Function

### ISSUE THREAD

**Issue by auksae** [skrafft/react-native-jitsi-meet#48]
Hi,

I successfully added Jitsi to my project thanks to you, and it works great. Really appreciate it!
Now I'm trying to allow users to be able to see other contents within my app while they are on a video call (on Jitsi) by creating a floating view, by making Jitsi re-sizable, or at least by letting users to minimize it. I do see a little arrow up in the screen which I assume should be used for the picture in picture function, but it does not work. Is there anyway I can make it work?
Please guide me on how I should go about it.

**Comment by skrafft** [comment]
Hi @auksae ,

Unfortunately, I don't think this is possible with the current structure of this library and with the sdk provided by jitsi (basically a full screen view for iOS and a full screen activity for android).
