### ISSUE TITLE
Throwing Error of CORS on running without Debugging  in React native 

### ISSUE THREAD

**Issue by Sandeep200995** [skrafft/react-native-jitsi-meet#49]

**Comment by Sandeep200995** [comment]
Its running properly when I run with remote debug mode but without it is not running on Debug mode or Release mode too

**Comment by skrafft** [comment]
@Sandeep200995 I cannot reproduce your problem. What's your version of React Native ?

**Comment by Sandeep200995** [comment]
0.60

**Comment by skrafft** [comment]
Duplicates #55
