### ISSUE TITLE
Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag

### ISSUE THREAD

**Issue by daravilo** [skrafft/react-native-jitsi-meet#5]
I'm getting this error on android. I followed every step and nothing works to solved this problem.

**Comment by daravilo** [comment]
Thanks, but I already solved the problem using **_intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);_**
in the call method before **_context.startActivity(intent);_**  and that's it. Everything works fine. But now I got a problem with ios.

**Comment by skrafft** [comment]
Perfect. So i'll update the code to add this line and publish a new version. Thanks for the feedback.
