### ISSUE TITLE
'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by hnrqsss** [skrafft/react-native-jitsi-meet#50]
RN: 60
node: 10.13.0
After i install and follow all the steps of manual installation on iOS it shows an error: 'React/RCTBridgeModule.h' file not found'. Untill now i can't find a solution, someone help me please?

**Comment by BarryOwens** [comment]
@hnrqsss Getting the same error. How did you resolve?

**Comment by hnrqsss** [comment]
This i solve importing React.
On XCode in left side:
right click on "libraries" -> "add file to your project" -> search your project/ node_modules/react-native/React/React.x....

After that go to Build Phases -> Target Dependencies and add React

Clean and Build again
