### ISSUE TITLE
JitsiMeetEvents "CONFERENCE_LEFT" event Not working

### ISSUE THREAD

**Issue by AymenBob** [skrafft/react-native-jitsi-meet#51]
Hello Skraft,
I installed react-native-jitsi-meet and use it but I was not able to retrieve the data of a call with JitsiMeetEvents => CONFERENCE_LEFT.
I think the listenner does not even detect the end or the stop of the call.
Thank you for announcing me if there is any solution for this.

**Comment by skrafft** [comment]
Hi, I just published V2.0.0 which has been completely re-architectured and is compatible with RN 0.60.

Please read the Readme file as the integration has changed: [README](https://github.com/skrafft/react-native-jitsi-meet/blob/master/README.md)
