### ISSUE TITLE
How end a call from code

### ISSUE THREAD

**Issue by jonnps** [skrafft/react-native-jitsi-meet#53]
I can't find a way of end a call directly from the code, this option exists?

**Comment by skrafft** [comment]
Hi @jonnps ,

Currently, Jitsi Meet SDK does not provide any means to end a call programmatically so this package cannot provide it as well. This does not seem to be in their roadmap.

Feel free to ask the Jitsi Meet team to include it in their sdk and I'll update this package to implement the feature.

**Comment by jonnps** [comment]
I saw in another topics that, if i load an null url, the conference ends.
>[1] (https://github.com/jitsi/jitsi-meet/issues/3595#issuecomment-436245917)
>[2] (https://community.jitsi.org/t/best-way-to-end-a-call-from-ios-or-android/15406/2)

But when i try to load an null url via _call_ method another Activity is created.
This behavior is expected because of **context.startActivity(intent)**

```
    public void call(String url) {
        ReactApplicationContext context = getReactApplicationContext();
        Intent intent = new Intent(context, JitsiMeetNavigatorActivity.class);
        intent.putExtra("url", url);
        intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        context.startActivity(intent);
    }
```
> java.lang.AssertionError: Pausing an activity that is not the current activity, this is incorrect! Current activity: JitsiMeetNavigatorActivity Paused activity: JitsiMeetNavigatorActivity

I think that if i can change the URL of ongoing call, the call ends. 

Is that incorrect?

**Comment by skrafft** [comment]
That could work. I did not know this trick. I don't have time to do it now but will re-open this ticket. Feel free to submit a PR if you have time to implement this feature.

**Comment by skrafft** [comment]
I just pushed this feature to master for iOS. Waiting android sdk for RN 0.60 to release everything at once.

**Comment by Frindecent** [comment]
@skrafft they released something new in android sdk using jsc artifacts. wouldnt there current sdk work with 0.60.5?

**Comment by skrafft** [comment]
@Frindecent So far, the last version of jitsi sdk for android is 2.2.2 ((https://github.com/jitsi/jitsi-maven-repository/tree/master/releases/org/jitsi/react/jitsi-meet-sdk) which will not work with RN 0.60 . I'm waiting for a new release to update this library. In the meantime, use RN0.59 with latest react-native-jitsi-meet version.

**Comment by skrafft** [comment]
Hi, I just published V2.0.0 which has been completely re-architectured and is compatible with RN 0.60.

An endCall function is now provided for both ios and android.

Please read the Readme file as the integration has changed: [README](https://github.com/skrafft/react-native-jitsi-meet/blob/master/README.md)

**Comment by hnrqsss** [comment]
> Hi, I just published V2.0.0 which has been completely re-architectured and is compatible with RN 0.60.
> 
> An endCall function is now provided for both ios and android.
> 
> Please read the Readme file as the integration has changed: [README](https://github.com/skrafft/react-native-jitsi-meet/blob/master/README.md)

This update solve this issue?

**Comment by skrafft** [comment]
Yes it does

**Comment by hnrqsss** [comment]
> Yes it does

Thanks man i 'll try it

**Comment by qtdevel** [comment]
Hi, can you help me please to end call from view controller, which holds JitsiMeetView? How can I do it? I don't understand.

**Comment by anshumanburman** [comment]
I also have the issue with call end, there is not any event are invoked after end the call.

**Comment by vinaygoyal20** [comment]
To all those who still face this issue, A new method is added and which is there in the example project 
https://github.com/skrafft/react-native-jitsi-meet/blob/master/ExampleApp/App.js

The method is end call i.e `JitsiMeet.endCall();`
And this method is i think is available in version>= 2.0.0

**Comment by vijay-subramani** [comment]
@skrafft we are using customised sdk. for android it's working fine. in iOS if i clicked hangup icon it juz loading.... Call ended but not get callled on jitsiMeetViewDelegate conferenceTerminated (_ data: [AnyHashable : Any]!) method.

**Comment by sagarsukode** [comment]
I am trying this two line of code but still not working, unable to end the call/conference.

jitsiMeetView?.leave()
jitsiMeetView?.hangUp()

Anyone found the solution?

**Comment by qtdevel** [comment]
Try to join with empty serverURL:

let options = JitsiMeetConferenceOptions.fromBuilder { builder in
        builder.serverURL = nil
}
self.jitsiMeetView.join(options)
