### ISSUE TITLE
How change url server ?

### ISSUE THREAD

**Issue by rajapulau** [skrafft/react-native-jitsi-meet#54]
Can I change url https://meet.jit.si to my own server url ? 

Regards

**Comment by skrafft** [comment]
Yes you can, just pass the full url of your server (including the room) in the call function:

```JitsiMeet.call('https://<your_server>/<room_name>')```

**Comment by abrantes01** [comment]
@skrafft Maybe can we add this in the Readme ? Looks like URL can be either the room_name (if we want to use Jitsi servers) or, if custom server needed, the entire url to the server + room_name
