### ISSUE TITLE
Custom Design for call.

### ISSUE THREAD

**Issue by Rana-Mohit** [skrafft/react-native-jitsi-meet#56]
Hi, @skrafft 
I need to customize the call screen design. I gone through your comments about customization and read both below points but didn't get how to  do that can you please give little more guide about how to do that.
1 - The clean one: Fork Jitsi Meet to change the source code and add custom flags to display or not the menu buttons.

2- The dirty one: Remove the menu buttons from the minified jitsi meet javascript source code when compiling your app

Any Help will be appreciated.

**Comment by skrafft** [comment]
What I currently do on my apps to achieve this goal is to use sed at build time to remove parts of the jitsi-meet javascript code which hides some feature. It's not clean, nor sustainable but so far it's proved very effective. A sample of the sed command can be found in #23.
