### ISSUE TITLE
The following binaries use incompatible versions of Swift:

### ISSUE THREAD

**Issue by daravilo** [skrafft/react-native-jitsi-meet#6]
**_The following binaries use incompatible versions of Swift:
/Users/username/Library/Developer/Xcode/DerivedData/projectname-fzxkxjqmxsouqfemxtbunkbsymhh/Build/Products/Debug-iphonesimulator/projectname.app/Frameworks/JitsiMeet.framework/JitsiMeet
/Users/username/Library/Developer/Xcode/DerivedData/projectname-fzxkxjqmxsouqfemxtbunkbsymhh/Build/Products/Debug-iphonesimulator/projectname.app/projectname_**

any solution to this problem only on ios it's works fine with android.

**Comment by skrafft** [comment]
Hi,

Can you tell me what XCode version you’re using ?

**Comment by daravilo** [comment]
I'm using xcode 9.2

**Comment by daravilo** [comment]
Yes I updated xcode and  it solved my problem, But now it says that config.h isn't found.

**Comment by daravilo** [comment]
yes the problem is with xcode 10. it kill all my project.

**Comment by saadqbal** [comment]
@daravilo have you got any success in using this library with realm ?

**Comment by daravilo** [comment]
Hello, we hasn't release our app yet, but it is working correctly.  But
some days ago we have some problems with the sdk of Jitsi on android, they
update the sdk , so the library was crashing when building for android. we
solved the problem changing in the library the sdk version of Jitsi and
that sit.

It's good you ask for feedback. This library has helped me a lot on others
projects adding native functionalities to react native apps, Thanks!!!!

**Comment by saadqbal** [comment]
Hi @daravilo Thanks for your response. have you tried this library with realm-js ? 

It does not work with realm-js
