### ISSUE TITLE
black screen for jitsi meet on ios 13

### ISSUE THREAD

**Issue by terrynip506** [skrafft/react-native-jitsi-meet#60]
Hi, the app appears in black when i test the video conferencing on ios13, any fix to it ? thanks 
my react-native version is 0.59.3.

**Comment by terrynip506** [comment]
and my jitsi version is 1.2.0

**Comment by djorkaeffalexandre** [comment]
We need to update the iOS SDK to version 2.3.0, I trying it now.

**Comment by djorkaeffalexandre** [comment]
@skrafft can you help me?

**Comment by skrafft** [comment]
I'll post a new version 2.0.1 with iOS SDK 2.3.0 tomorrow. I'll update this post when done.

**Comment by djorkaeffalexandre** [comment]
Ok, thanks! ❤️

**Comment by skrafft** [comment]
Hi, new version 2.0.1 is out and fixes this problem. Be sure to read the README file and add the right section in your metro.config.js to avoid conflict problems.

**Comment by djorkaeffalexandre** [comment]
Wow! Really nice man!! Thanks ❤️

**Comment by sowjanyaabburi** [comment]
Hi , I have implemented Jitsi Meet iOS sdk but still showing black screen I don't know what is going wrong in it can you please help me find out 

here is my code 

  let jitsiMeetView = JitsiMeetView()
        jitsiMeetView.delegate = self
        self.jitsiMeetView = jitsiMeetView
        let defaultOptions = JitsiMeetConferenceOptions.fromBuilder { (builder) in
                  // for JaaS replace url with https://8x8.vc
                  builder.serverURL = URL(string: "https://meet.jit.si") // instead of this I try with  my video url also 
                  builder.room = "1234"
                  // for JaaS use the obtained Jitsi JWT
                //   builder.token = ""
                  builder.welcomePageEnabled = false
            builder.audioMuted = false
            builder.videoMuted = false
          // view.allowsInlineMediaPlayback = true
                  // Set different feature flags
             //    builder.setFeatureFlag("toolbox.enabled", withBoolean: false)
              //  builder.setFeatureFlag("filmstrip.enabled", withBoolean: false)
        }
               
        JitsiMeet.sharedInstance().defaultConferenceOptions = defaultOptions
       // let vc = UIViewController()
      //  vc.modalPresentationStyle = .fullScreen
        view = jitsiMeetView
        // join room and display jitsi-call
        jitsiMeetView.join(options)
