### ISSUE TITLE
Doesn't link properly when RN is integrated with existing app

### ISSUE THREAD

**Issue by pranav0281999** [skrafft/react-native-jitsi-meet#61]
Hey Skrafft!

I have tried this library with an app created with react-native command and an android app where react-native was integrated later. It works if I use it in first case, it doesn't work if I use it with a android project where react-native was integrated later. I am following [this](https://facebook.github.io/react-native/docs/0.59/integration-with-existing-apps) doc while integrating RN.

Any directions on why this might be happening?

Platform: Android
react-native-jitsi-meet: 1.2.0
react-native: 0.59.4

**Comment by pranav0281999** [comment]
This is the error I get when I try to initialize JitsiMeet:

`TypeError: null is not an object (evaluating '_reactNativeJitsiMeet.default.initialize')
    
    This error is located at:
        in HelloWorld (at renderApplication.js:35)
        in RCTView (at View.js:45)
        in View (at AppContainer.js:98)
        in RCTView (at View.js:45)
        in View (at AppContainer.js:115)
        in AppContainer (at renderApplication.js:34)`

**Comment by arioki1** [comment]
> This is the error I get when I try to initialize JitsiMeet:
> 
> `TypeError: null is not an object (evaluating '_reactNativeJitsiMeet.default.initialize') This error is located at: in HelloWorld (at renderApplication.js:35) in RCTView (at View.js:45) in View (at AppContainer.js:98) in RCTView (at View.js:45) in View (at AppContainer.js:115) in AppContainer (at renderApplication.js:34)`

What version of react-native-jitsi-meet are you using

**Comment by skrafft** [comment]
Hi Pranav, did you check this part of the readme: https://github.com/skrafft/react-native-jitsi-meet#android-manual-install

It seems that jitsi is not loading the right javascript code

**Comment by pranav0281999** [comment]
Hi @skrafft, I followed all the steps properly. The problem was in how I was initializing react-native activities in native (java) code. It took some time to understand but eventually I made it work.

I am closing this issue and if anyone faces similar issues I will be happy to help.
