### ISSUE TITLE
Best version for RN 0.59

### ISSUE THREAD

**Issue by jmagdada** [skrafft/react-native-jitsi-meet#62]
Hello, may I know what is the best package version to use for RN 0.59? My project is still using this rn version and I dont have time yet to upgrade. I tried the latest version of the package but it does not work and so maybe because it does not compatible with my RN version. I look into the "releases" but I can't find any info. Pls help. Thanks alot!

**Comment by skrafft** [comment]
Hi @jmagdada, you want 1.2.0 for RN 0.59

**Comment by jmagdada** [comment]
Hi @skrafft thank you for your quick reply. I'll try this out. thank you

**Comment by rajapulau** [comment]
@skrafft If I use RN 0.57.2, which version I must install?

**Comment by skrafft** [comment]
1.1.1 but it will only work if you have Xcode < 10.2. Otherwise, you'll have to upgrade your RN version.

**Comment by rajapulau** [comment]
where did we know the configuration about support RN and Xcode version in this library @skrafft? I want to see the file.

Regards
