### ISSUE TITLE
RNJitsiMeetView was not found in the UIManager

### ISSUE THREAD

**Issue by youssefatti** [skrafft/react-native-jitsi-meet#63]
Hi @skrafft 

Step to reproduce:

I'm creating a new project:
react-native init MyProject
npm install react-native-jitsi-meet --save

added this 

const blacklist = require('metro-config/src/defaults/blacklist');

module.exports = {
  resolver: {
    blacklistRE: blacklist([
      /ios\/Pods\/JitsiMeetSDK\/Frameworks\/JitsiMeet.framework\/assets\/node_modules\/react-native\/.*/,
    ]),
  },
};

and your following code

npm run ios

Need help ;-)

Environment : 
    "react": "16.9.0",
    "react-native": "0.61.1",
    "react-native-jitsi-meet": "^2.0.1",

**Comment by skrafft** [comment]
I've updated the documentation for blank projects, please check: https://github.com/skrafft/react-native-jitsi-meet/blob/master/README.md

For iOS, you'll need to modify your Podfile to have ```platform :ios, '10.0'``` and execute ```pod install```

Be sure to follow iOS Configuration instructions in the README as well.
