### ISSUE TITLE
RNJitsiMeetView was not found in the UIManager

### ISSUE THREAD

**Issue by youssefatti** [skrafft/react-native-jitsi-meet#64]
Hi @skrafft,

Step to reproduce : 
- Create new RN project (react-native init MyProject)
- npm install react-native-jitsi-meet --save
- added this code 
const blacklist = require('metro-config/src/defaults/blacklist');

module.exports = {
  resolver: {
    blacklistRE: blacklist([
      /ios\/Pods\/JitsiMeetSDK\/Frameworks\/JitsiMeet.framework\/assets\/node_modules\/react-native\/.*/,
    ]),
  },
};

as you said here (iOS Manual Install (deprecated for RN >= 0.60)) i skip it

react-native run-ios

and i have this issue : 

<img width="299" alt="Screenshot 2019-09-30 at 21 11 52" src="https://user-images.githubusercontent.com/35220414/65948177-0125c780-e43a-11e9-91b5-31764ca78a04.png">

Environement:
    "react": "16.9.0",
    "react-native": "0.61.1",
    "react-native-jitsi-meet": "^2.0.1"

If anyone could help me.

Thanks

**Comment by skrafft** [comment]
For iOS, you'll need to modify your Podfile to have ```platform :ios, '10.0'``` and ```execute pod install```

Be sure to follow iOS Configuration instructions in the README as well or your app will crash directly.

**Comment by youssefatti** [comment]
when i did pod install i had this error 👍 

Unable to find a specification for `JitsiMeetSDK (= 2.3.0)` depended upon by `react-native-jitsi-meet'

**Comment by skrafft** [comment]
Did you change your Podfile to have ```platform :ios, '10.0'```? You probably have to run ```pod repo update``` to be sure that your sources are up-to-date.

**Comment by youssefatti** [comment]
@skrafft Thanks a lot. yes i added platform :ios, '10.0', pod repo update did the job for pod install but i had to set enable BITCODE to NO

**Comment by skrafft** [comment]
Thanks for the feedback. Glad to know it works.

**Comment by jean-ben-guigui** [comment]
The following is working for me:

   
    platform :ios, '10.0'
    require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

    target 'v06006' do
      # Pods for v06006
      pod 'React', :path => '../node_modules/react-native/'
      pod 'React-Core', :path => '../node_modules/react-native/React'
      pod 'React-DevSupport', :path => '../node_modules/react-native/React'
      pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
      pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
      pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
      pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
      pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
      pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
      pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
      pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
      pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
      pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

      pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
      pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
      pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
      pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
      pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

      pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
      pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
      pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

      target 'v06006Tests' do
        inherit! :search_paths
        # Pods for testing
      end

      use_native_modules!
    end

    target 'v06006-tvOS' do
      # Pods for v06006-tvOS

      target 'v06006-tvOSTests' do
        inherit! :search_paths
        # Pods for testing
      end

    end

**Comment by youssefatti** [comment]
@rcidt 
platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'JitsiMeetTest' do
  # Pods for JitsiMeetTest
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'JitsiMeetTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'JitsiMeetTest-tvOS' do
  # Pods for JitsiMeetTest-tvOS

  target 'JitsiMeetTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
