### ISSUE TITLE
Custom Framework

### ISSUE THREAD

**Issue by rajapulau** [skrafft/react-native-jitsi-meet#65]
Hi @skrafft 

I want to custom my JitsiMeet.framework. I see document [here](https://github.com/jitsi/jitsi-meet/tree/master/ios#builduing-it-yourself) . But I have a question if I build my own framework how an update to your library? Just copy and replace or there are have another step?

Regards,

**Comment by rajapulau** [comment]
![Screen Shot 2019-10-02 at 15 52 27](https://user-images.githubusercontent.com/958302/66030996-b9339d00-e52c-11e9-854f-6245997e547a.png)

I'm not an iOS developer. I got an error after I replace jitsiMeet.framework. what is the meaning of the error?

**Comment by skrafft** [comment]
Sorry, I don't really know what this error means. If you want to use your own SDK, you have to replace the jitsi-meet source url in build.gradle for android and you have to use a custom source for CocoaPods. It can be done but will probably cost you a lot of time.
