### ISSUE TITLE
The specified child already has a parent.

### ISSUE THREAD

**Issue by LeoMosiah** [skrafft/react-native-jitsi-meet#66]
When I run my android app on my own device it's rendering only a white screen, and when I reload my app I get this error message "The specified child already has a parent. You must call removeView() on the childs parent first"

**Comment by jean-ben-guigui** [comment]
Same here, have you found something?

**Comment by LeoMosiah** [comment]
I'm downgraded to  the 1.2.0 version.

**Comment by nicolaselorr** [comment]
I also encounter the same issue on the new update (2.0.1). I can downgrade but what I need in my project was to overlay a timer on top of the JitsiMeet view which can't be done in versions lower than 2.0.0. Help.

**Comment by Haseeb005** [comment]
Hi guys, I was facing this issue on my side also, But when i uninstall the App form mobile and rebuild the app it's gone. give it a try may this will help you.

**Comment by nicolaselorr** [comment]
I am still facing the same issue.

**Comment by polaris04** [comment]
"The specified child already has a parent. You must call removeView() on the childs parent first"

I fix the issue using Actions.pop();

**Comment by batuhansahan** [comment]
same issue here

**Comment by polaris04** [comment]
> > "The specified child already has a parent. You must call removeView() on the childs parent first"
> > I fix the issue using Actions.pop();
> 
> What do you mean Actions.pop()?
> 
> same issue here

Hi @batuhansahan its a routing issue you need to properly close the page or scene after the call on my side I'm using `react-native-router-flux` you can check this link

so, for example, I have a page with JitsiMeetView called 'onCall'  after the call will move to next page called 'callExperience'

e.g 
inside onCall page 

goToCallExperience(){
Actions.replace('callExperience',{
startTIme:this.props.startTime,
endTime:this.props.endTIme
})
}

Reference

https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md#actions

**Comment by MisterFredy** [comment]
> > > "The specified child already has a parent. You must call removeView() on the childs parent first"
> > > I fix the issue using Actions.pop();
> > 
> > 
> > What do you mean Actions.pop()?
> > same issue here
> 
> Hi @batuhansahan its a routing issue you need to properly close the page or scene after the call on my side I'm using `react-native-router-flux` you can check this [link](https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md#actions)
> 
> so, for example, I have a page with JitsiMeetView called 'onCall' after the call will move to next page called 'callExperience' either you use Actions.replace or Actions.pop
> 
> e.g
> inside onCall page
> 
> goToCallExperience(){
> Actions.replace('callExperience',{
> startTIme:this.props.startTime,
> endTime:this.props.endTIme
> })
> }

hi polaris can you give me example how to do that? i still get the same issue

**Comment by MisterFredy** [comment]
i think this issue when we debugging last screen not close from jitsi so you found this error.i can modify this script but please give me clue where is this view show on node modules script?

**Comment by aaryavrate** [comment]
I face issue when the JitsiMeetView is loaded
