### ISSUE TITLE
Can't build Android in release mode. 

### ISSUE THREAD

**Issue by zayedelfasa** [skrafft/react-native-jitsi-meet#72]
Hi skrafft. Nice to use your library.

But, i have a problem when i use async-storage (package from : @react-native-community/async-storage).

When i release my android application (format *.aab) there is error like this : 

![Clipboard - October 28, 2019 10_56 AM](https://user-images.githubusercontent.com/5457383/67651076-00694e00-f972-11e9-8810-d2a0741dbd93.png)

then, i looking for jitsi app dependencies.

i get one : 
<img width="571" alt="Screen Shot 2019-10-28 at 10 52 04" src="https://user-images.githubusercontent.com/5457383/67651098-15de7800-f972-11e9-877b-b8ffeeadb5dd.png">

i want to ask how to handle crash this problem?

my nodemodules:

"dependencies": {
    "@react-native-community/async-storage": "^1.5.0",
    "react": "16.8.6",
    "react-native": "^0.60.5",
    "react-native-jitsi-meet": "^2.0.0"
  }

**Comment by skrafft** [comment]
Hi @zayedelfasa,

You probably need to exclude async storage from jitsi by adding this piece of code: 

```
implementation(project(':react-native-jitsi-meet')) {
      exclude group: 'com.facebook.react',module:'react-native-community-async-storage'
    }
```

**Comment by jean-ben-guigui** [comment]
Add this in android/app/build.gradle as if you were not using autolinking.
You may also need to add the following in android/seetings.gradle
`include ':react-native-jitsi-meet'
project(':react-native-jitsi-meet').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-jitsi-meet/android')`

**Comment by zayedelfasa** [comment]
Hay @skrafft , thanks for helping me. its solved! :)

**Comment by letaptravek** [comment]
Hi @zayedelfasa , Can you please help me on how you got it working for RN 0.60.5. Thanks

I have fresh RN app only installed react-native-jitsi-meet.

RN: 0.60.5
react-native-jitisi-meet: 2.0.0

I get below error.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not determine artifacts for org.jitsi.react:jitsi-meet-sdk:2.3.0: Skipped due to earlier error

**Comment by jean-ben-guigui** [comment]
@zayedelfasa when you say it’s solved you mean that you can build in release mode or that you can build run and launch a Jitsi conference successfully in release mode?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kanivel** [comment]
> Hi @zayedelfasa,
> 
> You probably need to exclude async storage from jitsi by adding this piece of code:
> 
> ```
> implementation(project(':react-native-jitsi-meet')) {
>       exclude group: 'com.facebook.react',module:'react-native-community-async-storage'
>     }
> ```
Hay @skrafft ,

                      I can genearate release apk by excluding react-native-community-async-storage.but got crash when jitsi video call connected.any solution for this?.

**Comment by subhash4android** [comment]
Build issue solved. but app is crashing while launching in release mode.
Any solution for this.

Thanks.
