### ISSUE TITLE
Unable to run `react-native start`. Complains about jest-haste-map

### ISSUE THREAD

**Issue by rcidt** [skrafft/react-native-jitsi-meet#73]
Have added the package to my project and attempted to run the app on iOS.

I have tried cleaning the project, removing the `ios/build` directory, deintegrating and reinstalling pods, etc.

No matter what I do I receive the following when running `react-native start`

```
Loading dependency graph...jest-haste-map: Haste module naming collision: react-native
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/node_modules/react-native/package.json
    * <rootDir>/ios/build/liveninjaMessengerMobile/Build/Products/Debug-iphonesimulator/liveninjaMessengerMobile.app/Frameworks/JitsiMeet.framework/assets/node_modules/react-native/package.json

Failed to construct transformer:  { Error: Duplicated files or mocks. Please check the console for more info
    at setModule (/Users/rcorrie/workspace/liveninjaMessengerMobile/node_modules/jest-haste-map/build/index.js:620:17)
    at workerReply (/Users/rcorrie/workspace/liveninjaMessengerMobile/node_modules/jest-haste-map/build/index.js:691:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  mockPath1: 'node_modules/react-native/package.json',
  mockPath2: 'ios/build/liveninjaMessengerMobile/Build/Products/Debug-iphonesimulator/liveninjaMessengerMobile.app/Frameworks/JitsiMeet.framework/assets/node_modules/react-native/package.json' }
(node:16252) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Duplicated files or mocks. Please check the console for more info
(node:16252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Here is what my `metro.config.js` looks like:

```javascript
const blacklist = require('metro-config/src/defaults/blacklist');

module.exports = {
    resolver:{
        blacklistRE: blacklist([
            /node_modules\/.\/node_modules\/react-native\/./,
            /ios\/Pods\/JitsiMeetSDK\/Frameworks\/JitsiMeet.framework\/assets\/node_modules\/react-native\/.*/,
        ])
    },
    transformer: {
        getBlacklistRE: () => {
            blacklist([
                /node_modules\/.\/node_modules\/react-native\/./,
                /nodejs-assets\/./,
                /android\/./,
                /ios\/./,
                /node_modules\/.\/node_modules\/react-native\./,
                /android\/./,
                /ios\/Pods\/JitsiMeetSDK\/Frameworks\/JitsiMeet.framework\/assets\/node_modules\/react-native\/.*/,
            ])
        },
        getTransformOptions: async () => ({
            transform: {
                experimentalImportSupport: false,
                inlineRequires: false,
            },
        }),
    },
};
```

**Comment by jean-ben-guigui** [comment]
The problem is definitely coming from metro config.
Try with something like this, it's working fine for me:

    /**
     * Metro configuration for React Native
     * https://github.com/facebook/react-native
     *
     * @format
     */

    const blacklist = require('metro-config/src/defaults/blacklist');

    module.exports = {
      transformer: {
        getTransformOptions: async () => ({
          transform: {
            experimentalImportSupport: false,
            inlineRequires: false,
          },
        }),
      },
      resolver: {
        blacklistRE: blacklist([
          /ios\/Pods\/JitsiMeetSDK\/Frameworks\/JitsiMeet.framework\/assets\/node_modules\/react-native\/.*/,
        ]),
      },
    };

**Comment by rcidt** [comment]
@jean-ben-guigui I managed to overcome this by upgrading to latest RN version.

**Comment by nvme978** [comment]
Well this ticket is closed, but I found a fix which does not involve upgrading RN. 

If you look at the error message closely, the path in the message is different from what we have put in the `metro.config.js` file. 

Error msg: `/ios/build/liveninjaMessengerMobile/Build/Products/Debug-iphonesimulator/liveninjaMessengerMobile.app/Frameworks/JitsiMeet.framework/assets/node_modules/react-native/package.json`

File: `/ios\/Pods\/JitsiMeetSDK\/Frameworks\/JitsiMeet.framework\/assets\/node_modules\/react-native\/.*/`

We need to add the path in the error message to our configuration.
