### ISSUE TITLE
ReadMe Update

### ISSUE THREAD

**Issue by jean-ben-guigui** [skrafft/react-native-jitsi-meet#74]
Hello,

I and some others have added informations to build and run properly Android with react-native-jitsi-meet in version >=2.0.0. Confer #72, #67.

I think an update of the readMe would be a great idea. 
Do you agree @skrafft? If so, would you rather do it yourself or do you want me to do it?

Thanks again for your work, I greatly appreciate it.

**Comment by skrafft** [comment]
Hi @jean-ben-guigui,

I totally agree with you to update the readme. My time is very limited at the moment so I'd be happy to merge a pull request that updates the readme with the proper doc for 2.0.

Thanks.

**Comment by jean-ben-guigui** [comment]
okay, I'll get to it as soon as I can, probably this week end.

**Comment by jean-ben-guigui** [comment]
The pull request has been made #78 😃

**Comment by skrafft** [comment]
Many thanks for the pull request. I just merged it.
