### ISSUE TITLE
(ANDROID) RNJitsiMeetView was not found in the UIManager

### ISSUE THREAD

**Issue by zayedelfasa** [skrafft/react-native-jitsi-meet#75]
hi @skrafft , i have a problem when open the screen for my videocall in android. 

When i open it, there is error like this :
![d7389c14-d01a-4ec1-8a9e-50cb46da25d4](https://user-images.githubusercontent.com/5457383/67918164-cbf1ce00-fbcd-11e9-939a-73e179a18097.jpeg)

i have written the code in metro.config.js but until now i have same error.
can you help me ?

my node modules :
react-native: 0.61.2
react-native-jitsi-meet: 2.0.1

thank you!

**Comment by jean-ben-guigui** [comment]
Do you have this line at the top of your file?

    import JitsiMeet, { JitsiMeetView } from 'react-native-jitsi-meet';

And do you have a JitsiMeetView component rendered when you call `JitsiMeet.call`?

**Comment by zayedelfasa** [comment]
Hi @jean-ben-guigui 
yes i have written the code on top. 

this is my code : 
<img width="1094" alt="Screen Shot 2019-10-31 at 16 13 53" src="https://user-images.githubusercontent.com/5457383/67934003-8814be00-fbf9-11e9-82ea-879e495c3221.png">

**Comment by jean-ben-guigui** [comment]
Your code looks fine, I don't know what to say 😕

**Comment by gen-failure** [comment]
Is there a chance you installed react-native-jitsi-meet, but did not rebuild android package?

**Comment by zayedelfasa** [comment]
@gen-failure, i have been rebuild android package with command "./gradlew clean" after install this package. Any wrong on my code ?

**Comment by gen-failure** [comment]
@zayedelfasa just to be sure, try to clean as you did, uninstall app on device and run react-native run android again. I will try to look on your code meanwhile, maybe I will have some idea.

**Comment by zayedelfasa** [comment]
Hi All, thanks for the answer. I think i have some wrong code in my project. I know new feature in RN > 0.60.0 is autolinking. But i make react-native-jitsi-meet non-autolinking in my project, because that i have error code. Now there is no error code anymore. Thanks~!

**Comment by peererror** [comment]
I having the same issue 
![image](https://user-images.githubusercontent.com/12954109/71096450-253eac80-21d0-11ea-9a33-44f96dcf2884.png)
I have updated my expo app from sdk 35 to 36 and I using bare frame bare workflow is there any specific steps after that

**Comment by Afondevi** [comment]
Same probleme...
