### ISSUE TITLE
2018-10-12 15:00:34.803988-0400 OPTIC[18931:3761266] Load URL https://meet.jit.si/serviciosenlinea 2018-10-12 15:00:34.826396-0400 OPTIC[18931:3761076] Unknown class JitsiMeetView in Interface Builder file

### ISSUE THREAD

**Issue by daravilo** [skrafft/react-native-jitsi-meet#8]
Getting this error  on ios any Idea here the complete log:

_**2018-10-12 15:00:34.804 [info][tid:com.facebook.react.RNJitsiMeetNavigatorManagerQueue][RNJitsiMeetNavigator.m:56] Load URL https://meet.jit.si/serviciosenlinea
2018-10-12 15:00:34.803988-0400 OPTIC[18931:3761266] Load URL https://meet.jit.si/serviciosenlinea
2018-10-12 15:00:34.826396-0400 OPTIC[18931:3761076] Unknown class JitsiMeetView in Interface Builder file.
2018-10-12 15:00:34.828725-0400 OPTIC[18931:3761076] -[UIView setDelegate:]: unrecognized selector sent to instance 0x7fef90c03130
2018-10-12 15:00:34.870963-0400 OPTIC[18931:3761076] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView setDelegate:]: unrecognized selector sent to instance 0x7fef90c03130'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000011106712b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010ff87f41 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001110e8024 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   UIKit                               0x0000000113f11f51 -[UIResponder doesNotRecognizeSelector:] + 295
	4   CoreFoundation                      0x0000000110fe9f78 ___forwarding___ + 1432
	5   CoreFoundation                      0x0000000110fe9958 _CF_forwarding_prep_0 + 120
	6   OPTIC                               0x000000010c55d94a -[JitsiMeetViewController setDelegate:] + 106
	7   OPTIC                               0x000000010c55e319 __36-[RNJitsiMeetNavigatorManager call:]_block_invoke + 297
	8   libdispatch.dylib                   0x0000000115f8433d _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x0000000115f913a0 _dispatch_sync_thread_bound_invoke + 386
	10  libdispatch.dylib                   0x0000000115f8433d _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x0000000115f8f5f9 _dispatch_main_queue_callback_4CF + 628
	12  CoreFoundation                      0x0000000111029e39 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	13  CoreFoundation                      0x0000000110fee462 __CFRunLoopRun + 2402
	14  CoreFoundation                      0x0000000110fed889 CFRunLoopRunSpecific + 409
	15  GraphicsServices                    0x0000000116cab9c6 GSEventRunModal + 62
	16  UIKit                               0x0000000113cde5d6 UIApplicationMain + 159
	17  OPTIC                               0x000000010c55d870 main + 112
	18  libdyld.dylib                       0x0000000116000d81 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException**_

**Comment by skrafft** [comment]
```
Unknown class JitsiMeetView in Interface Builder file.
```

It seems that you did not import the react-native-jitsi-meet project in your XCode environment. Can you check that the manual install procedure was done correctly ?

**Comment by skrafft** [comment]
Closing because this thread is not active anymore
