### ISSUE TITLE
Custom UI

### ISSUE THREAD

**Issue by jean-ben-guigui** [skrafft/react-native-jitsi-meet#80]
Hi there,

I read about #56 and #23. I want to modify a bit Jitsi UI.
So I decided to Fork Jitsi Meet to modify some pieces of code.

I followed the following [documentation](https://github.com/jitsi/jitsi-meet/blob/master/android/README.md#build-and-use-your-own-sdk-artifactsbinaries) and successfully managed to make it work on android.

Then I built a new JitsiMeet ios SDK using the command described [here](https://github.com/jitsi/jitsi-meet/tree/master/ios#builduing-it-yourself).
But now that I have my sdk, I'm wondering how to replace the default one of react-native-jitsi-meet.
I first tried to switch it within the Pods directory of my project:
![image](https://user-images.githubusercontent.com/15104156/68313875-99f0d800-00b5-11ea-8b3e-f2baac9e84ca.png)
But the changes don't apply when I run my app.

So I looked in node_modules/react-native-jitsi-meet/ios but the sdk don't seem to be there:
![image](https://user-images.githubusercontent.com/15104156/68313769-6ca42a00-00b5-11ea-830a-9e47b436f8e4.png)
So I opened directly RNJitsiMeet.xcodeproj in Xcode. and tried to change JitsiMeet.framework directly in there. Still don't have my changes poping on the screen then :(

I am going to keep on trying, but if you happened to know just the thing to do, I would highly appreciate your help!

**Comment by jean-ben-guigui** [comment]
Eventually got it to work.
The actual location of the framework is `/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework`
I'm still wondering how to properly commit my new JitsiMeet.framework to my repo so that new people that get my repo and run pod install get the right JitsiMeet.framework.

**Comment by batuhansahan** [comment]
I fork Jitsi-meet modified for android remove some buttons in Option button, which found in react/toolbar/ some files ending with  .native.js and built the sdk and using it with no error but my changes didn't apply, whats my fault?

**Comment by antoinefotso** [comment]
@batuhansahan  you finally achieved it ?

**Comment by batuhansahan** [comment]
> @batuhansahan you finally achieved it ?

yes i did

**Comment by aayush123** [comment]
> > @batuhansahan you finally achieved it ?
> 
> yes i did

Please provide details about how you achieved it

**Comment by alexstoyanov** [comment]
@jean-ben-guigui @batuhansahan did somebody got it working for iOS? I am stuck with that...

**Comment by jean-ben-guigui** [comment]
If your problem is this one :
> I'm still wondering how to properly commit my new JitsiMeet.framework to my repo so that new people that get my repo and run pod install get the right JitsiMeet.framework.

Then I achieved this by creating a script that erase the JitsiMeet.framework and copy the right one at the specified location. I added a build phase that runs that script so that it is run everytime the app is run.

**Comment by alexstoyanov** [comment]
@jean-ben-guigui could you provide that script please?

**Comment by jean-ben-guigui** [comment]
unfortunately I have no access to this code right now.
it was a bash script that was basically
```
rm /ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework
cp path/to/your/framework  /ios/Pods/JitsiMeetSDK/Frameworks
```

**Comment by ealbers** [comment]
I dont have a JitsiMeetSDK directory in Pods. I am able to build and run the code but the changes I made to the UI are not updated. Any help would be awesome.

**Comment by jean-ben-guigui** [comment]
Oh, what version of react native and what version of react-native-jitsi-meet are you using?

**Comment by shamoons** [comment]
What about getting access to some of the events like the dominant speaker changing? Or getting participants?

**Comment by gaurav-psych** [comment]
are you able to customize the options in the react native jitsi meet options for react native?

**Comment by tvanhuu** [comment]
> unfortunately I have no access to this code right now.
> it was a bash script that was basically
> 
> ```
> rm /ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework
> cp path/to/your/framework  /ios/Pods/JitsiMeetSDK/Frameworks
> ```

Thank you. It worked <3

**Comment by tuladharjaa** [comment]
> unfortunately I have no access to this code right now.
> it was a bash script that was basically
> 
> ```
> rm /ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework
> cp path/to/your/framework  /ios/Pods/JitsiMeetSDK/Frameworks
> ```

What are the other steps after replace the file?
As the new framework filename is JitsiMeetSDK.framework and the previous was JItsiMeet.framework

**Comment by 31Karishma** [comment]
@jean-ben-guigui when I replace framework with new customized framework getting error like this.
anyone can help please.
![image](https://user-images.githubusercontent.com/61228236/120794807-5478e300-c556-11eb-8607-3c545f1d2e56.png)

**Comment by techychen** [comment]
@31Karishma did you solve the problem?

**Comment by techychen** [comment]
I could solve the problem by changing the script a little.
```
rm -rf $(dirname "$0")/../ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework
cp -r $(dirname "$0")/JitsiMeet.framework $(dirname "$0")/../ios/Pods/JitsiMeetSDK/Frameworks
```
This is where my `jitsi.sh` is located.

![image](https://user-images.githubusercontent.com/84860257/133179976-9c9edf6d-4c35-4fbb-9d03-b60fe4a9bc8d.png)

**Comment by Shahzadali062** [comment]
@ealbers @shamoons @aayush123 @alexstoyanov @jean-ben-guigui  Any Solution for  Android  to change color of chat messages
