### ISSUE TITLE
Component VideoCall white screen

### ISSUE THREAD

**Issue by arioki1** [skrafft/react-native-jitsi-meet#82]
Hey skrafft

why when navigating to the VideoCall component nothing appears even though Jitseemet runs in the background even though the app is closed

![image](https://user-images.githubusercontent.com/1139881/68450349-574a0f80-021d-11ea-9e41-b766235fd1fc.png)

**Comment by arioki1** [comment]
When I try to make a Component VideoCall that runs on react native, the result is the same
![image](https://user-images.githubusercontent.com/1139881/68452738-0985d500-0226-11ea-9ae8-a580b9c0c681.png)

**Comment by arioki1** [comment]
![image](https://user-images.githubusercontent.com/1139881/68454133-4ce24280-022a-11ea-8c6c-9d7ac6f1b18f.png)

**Comment by jean-ben-guigui** [comment]
Try to put some `flex: 1` on everything that englobes  the JistimeetView component.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by imran1992** [comment]
tried. still white screen.

**Comment by arioki1** [comment]
![image](https://user-images.githubusercontent.com/1139881/68460961-b74fae80-023b-11ea-960e-ee708c6ce499.png)
there is already flex 1

**Comment by arioki1** [comment]
this  my repo https://github.com/arioki1/new-react-native-jitsi

**Comment by arioki1** [comment]
![image](https://user-images.githubusercontent.com/1139881/68462876-10214600-0240-11ea-8465-838515e30128.png)

**Comment by jean-ben-guigui** [comment]
Is there a `flex: 1` on the parent and the parent of the parent and so on?

**Comment by arioki1** [comment]
> <View style={{ backgroundColor: 'black', flex: 1 }}>
>           <JitsiMeetView onConferenceTerminated={this.onConferenceTerminated} onConferenceJoined={this.onConferenceJoined} onConferenceWillJoin={this.onConferenceWillJoin} style={{ flex: 1, height: '100%', width: '100%' }} />
> </View>

thanks bro, readme seems to be updated
