### ISSUE TITLE
How to auto authenticate openfire-ofmeet-plugin？

### ISSUE THREAD

**Issue by kangkfly** [skrafft/react-native-jitsi-meet#86]
I am using Openfire Meetings plugin, I want to automatically authenticate the users as they are already logged in to the react native app, but I can't find a way to auto authenticate Jitsi.

**Comment by skrafft** [comment]
I don't think this is supported by the official Jitsi Meet SDK yet. This lib is just a wrapper on top of the SDK. You'll have to open an issue in this repo: https://github.com/jitsi/jitsi-meet
