### ISSUE TITLE
JitsiView show black screen on Android

### ISSUE THREAD

**Issue by letruongkimtai** [skrafft/react-native-jitsi-meet#88]
Hi Skrafft. I have already using your library to my project on IOS platform, it works very smooth.

But I have a problem on Android that when i do a video call, everything is fine except JitsiView show only a black screen after connected to server. What i have is only sound. 

Looking forward for your response, Thank you so much...!!!

My node_modules:
- "react-native-jitsi-meet": "2.0.2"
- "react-native": "0.61.4"

![1575277596234 (1)](https://user-images.githubusercontent.com/34258524/70591019-2f2c4280-1c07-11ea-97e4-1dc62e152dd5.JPEG)

**Comment by skrafft** [comment]
Usually, this problem can have 2 different sources:

- View wrapper does not have the correct size. Check this issue for the solution: #82 
- You did not grant access to the camera. Please make sure that you did.

**Comment by letruongkimtai** [comment]
Thank you for your fast reply, Skrafft..!!

About your 2 solutions:
   - I have already cover JitsiView with a modal and set it flex to 1 and also with JitsiView. Like i said it work very smooth on IOS but sadly not for Android.
![image](https://user-images.githubusercontent.com/34258524/70692318-ab995100-1ced-11ea-8901-837ad5a4334a.png)


   - Should camera and microphone asked for permission before access JitsiView ? You remind me about permissions made me re-thinking about that problem. Cause it asked for permissions after i've launched JitsiView about 1~2 seconds.

Once again, Thank you so much..!!

**Comment by skrafft** [comment]
I've never tried to use it in a modal. We use it in a separate screen on which we navigate. Can you try to check the size of JitsiMeetView with a debugger ? Modals are not implemented the same way on iOS and on Android, that's why we use a separate screen.

**Comment by letruongkimtai** [comment]
Wow... I've never knew that modal would work different ways on different platform. I will try your solution right away. Thanks bro, you made my day!!

**Comment by letruongkimtai** [comment]
Hi Skrafft. Thanks for your solution. I have moved my JitsiView to screen instead of modal and it work perfectly. I will close this issue and once more time, thank you for giving me solution and knowledge to resolve this issue <3
