### ISSUE TITLE
leave conference manually

### ISSUE THREAD

**Issue by riobijanero** [skrafft/react-native-jitsi-meet#9]
I noticed that the app crashes when I press the home button of the phone while I am in a meet conference and then open the app again.
(Error: `'NSInvalidArgumentException', reason: 'Pushing the same view controller instance more than once is not supported`)
I assume, this is because the conference was not left properly and the view controller was not popped.
Do you know about a way to leave the conference that I can manually invoke when the app goes to background?

I have added this code to the JitsiMeetNavigator.m and I call leaveConference() when the App goes to the background, but that doesn't fix it.

```RCT_EXPORT_METHOD(leaveConference)
{
  dispatch_sync(dispatch_get_main_queue(), ^{
    RCTLogInfo(@"Conference left");
    UIViewController* rootViewController = [[[[UIApplication sharedApplication]delegate] window] rootViewController];
    UINavigationController *navigationController = (UINavigationController *) rootViewController;
    [navigationController popViewControllerAnimated:NO];
  });
}```

**Comment by skrafft** [comment]
No answer, closing
