### ISSUE TITLE
App crash when bundle

### ISSUE THREAD

**Issue by minh265tv** [skrafft/react-native-jitsi-meet#92]
My app (android) run in debug mode properly
But when i excute 'react bundle' then run app , my app has stopped 
`
react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`

I run on react-native 0.61.5 and react-native-jitsi-meet 2.0.2
Please help me!

**Comment by srajesh02529** [comment]
@minh265tv this issue is fixed?i am facing same issue. Debug mode it's working fine but Release build it's crashing.
