### ISSUE TITLE
Custom view and options

### ISSUE THREAD

**Issue by tuonght93** [skrafft/react-native-jitsi-meet#93]
How can I custom view incall and show any option i want?

**Comment by skrafft** [comment]
@tuonght93 

You have to fork the jitsi meet project jitsi-meet, customize it, built it and use the framework file (iOS) and the aar (Android) to replace the ones that come with this plugin.

@jean-ben-guigui  has done it if I'm not mistaken. Maybe he can help you.

**Comment by jean-ben-guigui** [comment]
Hi,
Yes, I have done it. What I did is just what @skrafft explained.
To help you, you can use the explanations in the jitsi meet repo:

- To [build android](https://github.com/jitsi/jitsi-meet/tree/master/android#build-and-use-your-own-sdk-artifactsbinaries) 

- To [build iOS](https://github.com/jitsi/jitsi-meet/tree/master/ios#builduing-it-yourself)
Here you cannot just add the JitsiMeet.framework to your project as they say. This is because the framework now comes from a podspec. What I did is add a "run script" phase to the build phases of my project. It launches a .sh file as follow:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/15104156/72148804-fddb9980-33a1-11ea-80cd-3f7bda04ffd5.png">

and Script.sh contains:

> rm -R ./Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework
> cp -R ./JitsiMeet.framework ./Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework

I hope that'll help you. If you have any question I'd be glad to help.

**Comment by SeveHo** [comment]
Many thanks man!

**Comment by tuonght93** [comment]
> Hi,
> Yes, I have done it. What I did is just what @skrafft explained.
> To help you, you can use the explanations in the jitsi meet repo:
> 
> * To [build android](https://github.com/jitsi/jitsi-meet/tree/master/android#build-and-use-your-own-sdk-artifactsbinaries)
> * To [build iOS](https://github.com/jitsi/jitsi-meet/tree/master/ios#builduing-it-yourself)
>   Here you cannot just add the JitsiMeet.framework to your project as they say. This is because the framework now comes from a podspec. What I did is add a "run script" phase to the build phases of my project. It launches a .sh file as follow:
> 
> <img alt="image" width="708" src="https://user-images.githubusercontent.com/15104156/72148804-fddb9980-33a1-11ea-80cd-3f7bda04ffd5.png">
> 
> and Script.sh contains:
> 
> > rm -R ./Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework
> > cp -R ./JitsiMeet.framework ./Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework
> 
> I hope that'll help you. If you have any question I'd be glad to help.

Thank @jean-ben-guigui , I have done it in iOS. but in android I have error about hermes engine. Do you have any idea?
![Screen Shot 2020-01-14 at 10 13 06](https://user-images.githubusercontent.com/20721876/72311332-d6910f00-36b6-11ea-827d-d722a17d01ba.png)

**Comment by tuonght93** [comment]
@jean-ben-guigui Thank you so much for your help! I have done it.

**Comment by SeveHo** [comment]
@jean-ben-guigui I followed your instruction and it works perfekt for debug and release builds but when I want to archive the app I get the following error: 

```
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_JitsiMeetConferenceOptions", referenced from:
      objc-class-ref in libreact-native-jitsi-meet.a(RNJitsiMeetViewManager.o)
  "_OBJC_CLASS_$_JitsiMeetView", referenced from:
      _OBJC_CLASS_$_RNJitsiMeetView in libreact-native-jitsi-meet.a(RNJitsiMeetView.o)
  "_OBJC_METACLASS_$_JitsiMeetView", referenced from:
      _OBJC_METACLASS_$_RNJitsiMeetView in libreact-native-jitsi-meet.a(RNJitsiMeetView.o)
ld: symbol(s) not found for architecture armv7
```

<img width="743" alt="Bildschirmfoto 2020-01-14 um 15 18 51" src="https://user-images.githubusercontent.com/20375523/72352090-ed992680-36e1-11ea-8de0-464cd677948e.png">


After removing the script from the build phases it works fine again.
Did you face the same issue or do you have an idea how to solve this?

**Comment by SeveHo** [comment]
Ok so I found out that the sdk I am building does not contain armv7.  Checked it like this: 

```bash
$ lipo -info ios/sdk/JitsiMeet.framework/JitsiMeet
Architectures in the fat file: ios/sdk/JitsiMeet.framework/JitsiMeet are: x86_64 arm64 
```

It a bit strange cause I use the build command provied by the Jitsi Team:
```bash
xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive
```

I am currently on XCode 11.3 with the same command line number.

@skrafft 
@jean-ben-guigui Did you do something differently while building the sources cause your sources seem to contain all architectures?

**Comment by jean-ben-guigui** [comment]
I never had such problem, it may be a settings that needs to be changed in your project.

I checked both jitsi meet and my project, they have the same configuration in build settings tab in the architecture area : 
![image](https://user-images.githubusercontent.com/15104156/72678929-be503400-3aaa-11ea-8a81-817966d6b6b0.png)

Also maybe check if this section is the same as mine:
![image](https://user-images.githubusercontent.com/15104156/72679015-6cf47480-3aab-11ea-9372-8a034a0f245d.png)

Hope this'll help.

**Comment by SeveHo** [comment]
Jitsi raised their deployment target to iOS 11. So when building their sdk it wont include a build for armv7 anymore. 
Hence I had to bump mine to iOS 11 as well in order to be able to submit the app to AppStore Connect. Doing so solved the problem.

Thanks for your answer!

**Comment by jean-ben-guigui** [comment]
Okay, glad you could make it work!
Your feedback will be of great help when we'll have to build it again, thanks :)

**Comment by SeveHo** [comment]
@jean-ben-guigui I just tried to use my custom build sdk in Android. I followed the documentation from [jitsi](https://github.com/jitsi/jitsi-meet/tree/master/android#build-and-use-your-own-sdk-artifactsbinaries).
The edited file inside `node_modules/react-native-jitsi-meet/android/build.gradle` looks like this:

```
...
repositories {
  maven {
      url "file:/tmp/repo"
  }
  google()
  mavenCentral()
  jcenter()
}

dependencies {
    implementation ('org.jitsi.react:jitsi-meet-sdk:+') {
      transitive = true
    }
}
...
```

As soon as I replace the maven url and the dependency the app crashes at the startup. How did you manage to replace the sdk?

**Comment by batuhansahan** [comment]
@SeveHo did you find the solution ?

**Comment by SeveHo** [comment]
@batuhansahan yep. Give me two days or so and I will document the way I did it in detail.

**Comment by rcidt** [comment]
@jean-ben-guigui do you know which files relate to the room options menu?

**Comment by batuhansahan** [comment]
features/toolbox

**Comment by SeveHo** [comment]
@batuhansahan have a look at this issue: https://github.com/skrafft/react-native-jitsi-meet/issues/106 The setup described there worked for me in the end.

**Comment by deepakverma4** [comment]
@jean-ben-guigui after replacing with custom sdk it is crashing giving this error ```[JitsiMeetSDK] FATAL ERROR: RCTFatalException: Unhandled JS Exception: TypeError: undefined is not an object (evaluating 'k.default.div.withConfig')```
Any guess how can we resolve it?

**Comment by bhavesh18** [comment]
> @tuonght93
> 
> You have to fork the jitsi meet project jitsi-meet, customize it, built it and use the framework file (iOS) and the aar (Android) to replace the ones that come with this plugin.
> 
> @jean-ben-guigui has done it if I'm not mistaken. Maybe he can help you.

Hi, I have customised the jitsi sdk and don't know how/where to replace the aar file for android. Could you please mention the directory path?

**Comment by kanelloc** [comment]
@jean-ben-guigui Hi After the build what files I should replace and where I can find them? Thank you

**Comment by tuladharjaa** [comment]
> Hi,
> Yes, I have done it. What I did is just what @skrafft explained.
> To help you, you can use the explanations in the jitsi meet repo:
> 
> * To [build android](https://github.com/jitsi/jitsi-meet/tree/master/android#build-and-use-your-own-sdk-artifactsbinaries)
> * To [build iOS](https://github.com/jitsi/jitsi-meet/tree/master/ios#builduing-it-yourself)
>   Here you cannot just add the JitsiMeet.framework to your project as they say. This is because the framework now comes from a podspec. What I did is add a "run script" phase to the build phases of my project. It launches a .sh file as follow:
> 
> <img alt="image" width="708" src="https://user-images.githubusercontent.com/15104156/72148804-fddb9980-33a1-11ea-80cd-3f7bda04ffd5.png">
> 
> and Script.sh contains:
> 
> > rm -R ./Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework
> > cp -R ./JitsiMeet.framework ./Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework
> 
> I hope that'll help you. If you have any question I'd be glad to help.

@jean-ben-guigui I have followed the above instructions on iOS and the build is success but I get this  error when I run it on iOS simulator I get the following

dyld`__abort_with_payload:
    0x119abfed4 <+0>:  movl   $0x2000209, %eax          ; imm = 0x2000209 
    0x119abfed9 <+5>:  movq   %rcx, %r10
    0x119abfedc <+8>:  syscall 
->  0x119abfede <+10>: jae    0x119abfee8               ; <+20>
    0x119abfee0 <+12>: movq   %rax, %rdi
    0x119abfee3 <+15>: jmp    0x119abe408               ; cerror_nocancel
    0x119abfee8 <+20>: retq   
    0x119abfee9 <+21>: nop    
    0x119abfeea <+22>: nop    
    0x119abfeeb <+23>: nop
