### ISSUE TITLE
App Crash in release builds Android

### ISSUE THREAD

**Issue by srajesh02529** [skrafft/react-native-jitsi-meet#97]
debug mode it's working fine but release builds it's crashing in android.How to solve this issue?

**Comment by skrafft** [comment]
Without more information, it's not possible to help you. My 2 cents is that you did not follow this guide: [Android Manual Install](https://github.com/skrafft/react-native-jitsi-meet#android-manual-install)

**Comment by srajesh02529** [comment]
@skrafft thanks for reply,i followed all the steps but no luck. and i am using the React Native 0.61.5 and below are my depedencies

dependencies {
    implementation project(':react-native-gesture-handler')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation ('org.jitsi.react:jitsi-meet-sdk:2.+') { transitive = true }
    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

**Comment by skrafft** [comment]
I need the following files to be able to help you (make sure to remove confidential info in the files if any):

- android/app/build.gradle
- android/app/src/main/java/com/xxx/MainApplication.java
- android/build.gradle

Thanks

**Comment by srajesh02529** [comment]
@skrafft [https://github.com/karthik-appliedsyntax/jitsiVideoCall](url)
This is my sample app, This app works fine in debug mode but in release mode it's crashing.
Thanks

**Comment by karthik-appliedsyntax** [comment]
@skrafft Hi here is the code

- android/app/build.gradel

`project.ext.react = [
    entryFile: "index.js",
    bundleAssetName: "app.bundle",
]
apply from: "../../node_modules/react-native/react.gradle"

def enableHermes = project.ext.react.get("enableHermes", false);
android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    defaultConfig {
        applicationId "com.lyvebeeconnect"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            storeFile file('/Users/appsynner/Desktop/projects/lyvebee react native/lyvebee.jks')
            storePassword 'lyvebee'
            keyAlias 'lyvebee'
            keyPassword 'lyvebee'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}
dependencies {
    implementation project(':@react-native-community_async-storage')
    implementation project(':react-native-gesture-handler')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation ('org.jitsi.react:jitsi-meet-sdk:2.+') { transitive = true }
    implementation "com.google.android.gms:play-services-base:16.1.0"
  implementation "com.google.firebase:firebase-core:17.2.2"
   implementation "com.google.firebase:firebase-messaging:20.1.0"
    implementation (project(':react-native-firebase')) {
       transitive = false
   }
    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}
// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
apply plugin: 'com.google.gms.google-services'`

- Main.Application.java
`import android.app.Application;
import android.content.Context;
import androidx.annotation.Nullable;
import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;
import java.lang.reflect.InvocationTargetException;
import java.util.List;
import io.invertase.firebase.messaging.RNFirebaseMessagingPackage;
import io.invertase.firebase.notifications.RNFirebaseNotificationsPackage;
public class MainApplication extends Application implements ReactApplication {
  private final ReactNativeHost mReactNativeHost =
      new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }
        @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
//           Packages that cannot be autolinked yet can be added manually here, for example:
//           packages.add(new MyReactNativePackage());
           packages.add(new RNFirebaseMessagingPackage());
           packages.add(new RNFirebaseNotificationsPackage());
          return packages;
        }
        @Override
        protected String getJSMainModuleName() {
          return "index";
        }
          @Override
          protected @Nullable
          String getBundleAssetName() {
              return "app.bundle";
          }
      };
  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }
  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    initializeFlipper(this); // Remove this line if you don't want Flipper enabled
  }
  /**
   * Loads Flipper in React Native templates.
   *
   * @param context
   */
  private static void initializeFlipper(Context context) {
    if (BuildConfig.DEBUG) {
      try {
        /*
         We use reflection here to pick up the class that initializes Flipper,
        since Flipper library is not available in release mode
        */
        Class<?> aClass = Class.forName("com.facebook.flipper.ReactNativeFlipper");
        aClass.getMethod("initializeFlipper", Context.class).invoke(null, context);
      } catch (ClassNotFoundException e) {
        e.printStackTrace();
      } catch (NoSuchMethodException e) {
        e.printStackTrace();
      } catch (IllegalAccessException e) {
        e.printStackTrace();
      } catch (InvocationTargetException e) {
        e.printStackTrace();
      }
    }
  }
}`

- android/build.gradel
`buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 28
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.2")
        classpath 'com.google.gms:google-services:3.2.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
        maven {
            url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases" 
        }
    }
}`

**Comment by josephJ2e** [comment]
I'm also encountering this. 

@srajesh02529 @karthik-appliedsyntax  were you able to find a solution?

**Comment by srajesh02529** [comment]
@josephJ2e i am taking separate project and followed the same tutorial.it's working.

**Comment by cristinaalexandru21** [comment]
@srajesh02529 how did you manage to make it work on Android? 
I downloaded your sample app from the link that you sent above (https://github.com/karthik-appliedsyntax/jitsiVideoCall), 
but when I run it in debug, the application crashes and closes when initiating the call.
Do you have any hints why that might happen?
thanks
